using Content.Shared.CMU14.ZLevels;
using Content.Shared._RMC14.CCVar;
using Content.Shared._RMC14.NightVision;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccessibilityTab : Control
{
    [Dependency] private IConfigurationManager _cfg = default!;

    private const float OldZLevelBlurStrength = 2.0f;

    public AccessibilityTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionCheckBox(CCVars.ReducedMotion, ReducedMotionCheckBox);
        Control.AddOptionCheckBox(CCVars.ExplosionScreenShakeEnabled, ExplosionScreenShakeEnabledCheckBox);
        Control.AddOptionCheckBox(CCVars.ExplosionScreenShakeIgnoreFar, ExplosionScreenShakeIgnoreFarCheckBox);
        ExplosionShakeOptions.DependOn(ExplosionScreenShakeEnabledCheckBox); // CMU
        Control.AddOptionCheckBox(CCVars.FirearmScreenShakeEnabled, FirearmScreenShakeEnabledCheckBox);

        Control.AddOptionCheckBox(CCVars.DisableAiStatic, DisableAiStaticCheckBox);
        Control.AddOptionCheckBox(CCVars.DisableBlurryVision, DisableBlurryVisionCheckBox);
        Control.AddOptionCheckBox(CCVars.DisableDrunkOverlay, DisableDrunkOverlayCheckBox);
        Control.AddOptionCheckBox(CCVars.DisableFlashEffect, DisableFlashEffectCheckBox);
        Control.AddOptionCheckBox(CCVars.DisableHeatDistortion, DisableHeatDistortionCheckBox);
        Control.AddOptionCheckBox(CCVars.DisableNightVisionNoise, DisableNightVisionNoiseCheckBox);
        Control.AddOptionCheckBox(CCVars.DisableRainbowOverlay, DisableRainbowOverlayCheckBox);
        Control.AddOptionCheckBox(CCVars.DisableSinguloWarp, DisableSinguloWarpCheckBox);

        Control.AddOptionPercentSlider(CCVars.ScreenShakeIntensity, ScreenShakeIntensitySlider);

        Control.AddOptionCheckBox(CCVars.AccessibilityColorblindFriendly, ColorblindFriendlyCheckBox);
        Control.AddOptionCheckBox(RMCCVars.RMCUseAlternateSprites, RMCUseAlternateSpritesCheckBox); // RMC14
        Control.AddOptionDropDown(
            RMCCVars.RMCNightVisionColor,
            RMCNightVisionColorDropDown,
            [
                new OptionDropDownCVar<int>.ValueOption((int) NightVisionColor.Green, Loc.GetString("rmc-ui-options-night-vision-color-green")),
                new OptionDropDownCVar<int>.ValueOption((int) NightVisionColor.Orange, Loc.GetString("rmc-ui-options-night-vision-color-orange")),
                new OptionDropDownCVar<int>.ValueOption((int) NightVisionColor.White, Loc.GetString("rmc-ui-options-night-vision-color-white")),
                new OptionDropDownCVar<int>.ValueOption((int) NightVisionColor.Yellow, Loc.GetString("rmc-ui-options-night-vision-color-yellow")),
                new OptionDropDownCVar<int>.ValueOption((int) NightVisionColor.Red, Loc.GetString("rmc-ui-options-night-vision-color-red")),
                new OptionDropDownCVar<int>.ValueOption((int) NightVisionColor.Blue, Loc.GetString("rmc-ui-options-night-vision-color-blue")),
            ]);

        RegisterAnnouncementOptions();

        Control.AddOptionPercentSlider(CMUZLevelsCVars.BlurStrength, ZLevelBlurSlider, scale: OldZLevelBlurStrength);
        Control.AddOptionPercentSlider(CMUZLevelsCVars.FaintUpperAlpha, FaintLookUpOpacitySlider, 0.05f, 0.80f);

        Control.AddOptionCheckBox(CCVars.AccessibilityClientCensorNudity, CensorNudityCheckBox);

        Control.Initialize();
    }
}
