using Content.Client.Administration.Managers;
using Content.Client.Audio;
using Content.Shared._Mono.CCVar;
using Content.Shared._RMC14.CCVar;
using Content.Shared.CCVar;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AudioTab : Control
{
    [Dependency] private IAudioManager _audio = default!;
    [Dependency] private IClientAdminManager _admin = default!;
    [Dependency] private IConfigurationManager _cfg = default!;

    private static readonly (string Loc, CVarDef<bool> Voiceline, CVarDef<bool> Emote)[] Species =
    {
        ("arachnid", RMCCVars.RMCPlayVoicelinesArachnid, RMCCVars.RMCPlayEmotesArachnid),
        ("avali", RMCCVars.RMCPlayVoicelinesAvali, RMCCVars.RMCPlayEmotesAvali),
        ("diona", RMCCVars.RMCPlayVoicelinesDiona, RMCCVars.RMCPlayEmotesDiona),
        ("dwarf", RMCCVars.RMCPlayVoicelinesDwarf, RMCCVars.RMCPlayEmotesDwarf),
        ("felinid", RMCCVars.RMCPlayVoicelinesFelinid, RMCCVars.RMCPlayEmotesFelinid),
        ("feroxi", RMCCVars.RMCPlayVoicelinesFeroxi, RMCCVars.RMCPlayEmotesFeroxi),
        ("human", RMCCVars.RMCPlayVoicelinesHuman, RMCCVars.RMCPlayEmotesHuman),
        ("moth", RMCCVars.RMCPlayVoicelinesMoth, RMCCVars.RMCPlayEmotesMoth),
        ("reptilian", RMCCVars.RMCPlayVoicelinesReptilian, RMCCVars.RMCPlayEmotesReptilian),
        ("rodentia", RMCCVars.RMCPlayVoicelinesRodentia, RMCCVars.RMCPlayEmotesRodentia),
        ("skrell", RMCCVars.RMCPlayVoicelinesSkrell, RMCCVars.RMCPlayEmotesSkrell),
        ("slime", RMCCVars.RMCPlayVoicelinesSlime, RMCCVars.RMCPlayEmotesSlime),
        ("vulpkanin", RMCCVars.RMCPlayVoicelinesVulpkanin, RMCCVars.RMCPlayEmotesVulpkanin),
    };

    public AudioTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionDropDown(CVars.AudioDevice, DropDownAudioDevice, BuildAudioDeviceOptions());

        var masterVolume = Control.AddOptionPercentSlider(
            CVars.AudioMasterVolume,
            SliderVolumeMaster,
            scale: ContentAudioSystem.MasterVolumeMultiplier);
        masterVolume.ImmediateValueChanged += OnMasterVolumeSliderChanged;

        Control.AddOptionPercentSlider(
            CVars.MidiVolume,
            SliderVolumeMidi,
            scale: ContentAudioSystem.MidiVolumeMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbientMusicVolume,
            SliderVolumeAmbientMusic,
            scale: ContentAudioSystem.AmbientMusicMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbienceVolume,
            SliderVolumeAmbience,
            scale: ContentAudioSystem.AmbienceMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.LobbyMusicVolume,
            SliderVolumeLobby,
            scale: ContentAudioSystem.LobbyMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.InterfaceVolume,
            SliderVolumeInterface,
            scale: ContentAudioSystem.InterfaceMultiplier);

        // RMC14
        Control.AddOptionPercentSlider(
            RMCCVars.VolumeGainCassettes,
            SliderVolumeCassettes,
            scale: 1f);

        Control.AddOptionPercentSlider(
            RMCCVars.VolumeGainHijackSong,
            SliderVolumeHijackSong,
            scale: 0.32f);

        Control.AddOptionSlider(
            CCVars.MaxAmbientSources,
            SliderMaxAmbienceSounds,
            _cfg.GetCVar(CCVars.MinMaxAmbientSourcesConfigured),
            _cfg.GetCVar(CCVars.MaxMaxAmbientSourcesConfigured));

        Control.AddOptionCheckBox(CCVars.LobbyMusicEnabled, LobbyMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.RestartSoundsEnabled, RestartSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.EventMusicEnabled, EventMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.MuteScriptedSounds, MuteScriptedSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.AdminSoundsEnabled, AdminSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.BwoinkSoundEnabled, BwoinkSoundCheckBox);
        Control.AddOptionCheckBox(CCVars.AudioHrtf, AudioHrtfCheckBox);
        Control.AddOptionCheckBox(CVars.AudioMuteUnfocused, MuteUnfocusedCheckBox);

        Control.AddOptionCheckBox(MonoCVars.AreaEchoEnabled, AreaEchoCheckBox); // Mono
        Control.AddOptionCheckBox(MonoCVars.AreaEchoHighResolution, AreaEchoHighResolutionCheckBox); // Mono
        AreaEchoOptions.DependOn(AreaEchoCheckBox); // CMU

        Control.AddOptionCheckBox(RMCCVars.RMCPlayVoicelinesYourself, RMCVoicelinesYourself);
        Control.AddOptionCheckBox(RMCCVars.RMCPlayEmotesYourself, RMCEmotesYourself);

        foreach (var (locId, voicelineCVar, emoteCVar) in Species)
        {
            var (voiceline, emote) = SpeciesMatrix.Add(Loc.GetString($"cmu-ui-options-species-{locId}"));
            Control.AddOptionCheckBox(voicelineCVar, voiceline);
            Control.AddOptionCheckBox(emoteCVar, emote);
        }

        SpeciesSection.Expanded = false;

        Control.Initialize();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _admin.AdminStatusUpdated += UpdateAdminButtonsVisibility;
        UpdateAdminButtonsVisibility();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _admin.AdminStatusUpdated -= UpdateAdminButtonsVisibility;
    }

    private void UpdateAdminButtonsVisibility()
    {
        BwoinkSoundCheckBox.Visible = _admin.IsActive();
    }

    private void OnMasterVolumeSliderChanged(float value)
    {
        // TODO: I was thinking of giving OptionsTabControlRow a flag to "set CVar immediately", but I'm deferring that
        // until there's a proper system for enforcing people don't close the window with pending changes.
        _audio.SetMasterGain(value);
    }

    private List<OptionDropDownCVar<string>.ValueOption> BuildAudioDeviceOptions()
    {
        var options = new List<OptionDropDownCVar<string>.ValueOption>();

        options.Add(new OptionDropDownCVar<string>.ValueOption(
            string.Empty,
            Loc.GetString("ui-options-audio-device-default")));

        foreach (var device in _audio.GetAudioDevices())
        {
            options.Add(new OptionDropDownCVar<string>.ValueOption(device, FormatAudioDeviceLabel(device)));
        }

        return options;
    }

    private static string FormatAudioDeviceLabel(string device)
    {
        const string openAlSoftPrefix = "OpenAL Soft on ";
        if (device.StartsWith(openAlSoftPrefix, StringComparison.Ordinal))
            return IAudioManager.ConvertAudioDeviceNameForDisplay(device);

        return device;
    }
}
