- type: entity
  parent: CMMobHuman
  id: CMUBaseMobSpeciesParamarines
  abstract: true
  suffix: CMU, TWE, Paramarines
  components:
  - type: GhostTakeoverAvailable
  - type: NpcFactionMember
    factions:
    - CMUTWE
  - type: RandomHumanoidAppearance

- type: entity
  parent: SquadPara
  id: CMUSquadParamarines
  name: Paramarines
  components:
  - type: SquadTeam
    group: Paramarines
