using System;
using System.Linq;
using Content.Client.Lobby.UI;
using Content.Client.CMU14.Interface;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.CMU14.Lobby;

/// <summary>
///     The faction choices, moved off the lobby panel and behind a single "Join the round" button.
///     Four wide buttons plus Observe, Rules and Guidebook made the lobby panel a seven-button slab;
///     the factions are one decision, taken once, so they belong in a popup rather than on the
///     permanent surface.
/// </summary>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class JoinRoundWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IStylesheetManager _stylesheetManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private const float ColumnWidth = 560f;

    private const int ColumnsPerRow = 2;

    private const int RowGap = 16;

    private const int TitleSize = 8;

    private const int ButtonTextSize = 8;

    private const float ScanlineDepth = 0.9f;

    /// <summary>
    ///     Colonists. The plain one on purpose - they are the default, least exotic choice, so it
    ///     gets a neutral grey-green rather than a faction colour. Being the only card with no hue
    ///     is itself the signal.
    /// </summary>
    private static readonly CmuChoiceCard.Palette ColonistsPalette = new(
        Color.FromHex("#5E6B64"), Color.FromHex("#0E1211"), Color.FromHex("#18201D"), Color.FromHex("#C2CCC6"));

    /// <summary>Govfor keeps the terminal green - it is the house faction and the theme's own hue.</summary>
    private static readonly CmuChoiceCard.Palette GovforPalette = new(
        Color.FromHex("#2E6241"), Color.FromHex("#0B1710"), Color.FromHex("#152F20"), Color.FromHex("#8FE9AE"));

    private static readonly CmuChoiceCard.Palette OpforPalette = new(
        Color.FromHex("#8C3038"), Color.FromHex("#170C0E"), Color.FromHex("#2A1417"), Color.FromHex("#FF9E9E"));

    /// <summary>Other - mostly xenomorphs, hence purple.</summary>
    private static readonly CmuChoiceCard.Palette OtherPalette = new(
        Color.FromHex("#5B4A8C"), Color.FromHex("#120E1B"), Color.FromHex("#1E1830"), Color.FromHex("#CDBCFF"));

    /// <summary>
    ///     Kept as properties because <see cref="Content.Client.Lobby.LobbyState"/> binds to them by
    ///     name. Backed by a field rather than a card now - see <see cref="BuildColumn"/>.
    /// </summary>
    public Button JoinColonistsButton { get; private set; } = default!;

    public Button JoinGovforButton { get; private set; } = default!;

    public Button JoinOpforButton { get; private set; } = default!;

    public Button JoinOtherButton { get; private set; } = default!;

    public Button JoinHuntButton { get; private set; } = default!;

    private PanelContainer _huntColumn = default!;

    private readonly List<(PanelContainer Column, Button Button, CmuChoiceCard.Palette Palette)> _columns = new();

    private CrtScreenControl _shaderPass = default!;

    private Control _cornerTicks = default!;

    public JoinRoundWindow()
    {
        Title = Loc.GetString("cmu-lobby-join-round-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Choices.SeparationOverride = RowGap;

        var row1 = ChoiceRow();
        var row2 = ChoiceRow();
        Choices.AddChild(row1);
        Choices.AddChild(row2);

        JoinColonistsButton = BuildColumn(row1, "lobby-state-ready-button-join-state", "cmu-lobby-join-colonists-desc", ColonistsPalette);
        JoinGovforButton = BuildColumn(row1, "rmc-lobby-join-govfor", "cmu-lobby-join-govfor-desc", GovforPalette);
        JoinOpforButton = BuildColumn(row2, "rmc-lobby-join-opfor", "cmu-lobby-join-opfor-desc", OpforPalette);
        JoinOtherButton = BuildColumn(row2, "rmc-lobby-join-other", "cmu-lobby-join-other-desc", OtherPalette);

        // The hunt rides below the grid, full width, and only for whitelisted players.
        var row3 = ChoiceRow();
        Choices.AddChild(row3);
        JoinHuntButton = BuildColumn(row3, "rmc-lobby-join-hunt", "cmu-lobby-join-hunt-desc", GovforPalette);
        _huntColumn = _columns[^1].Column;
        _huntColumn.HorizontalExpand = true;
        _huntColumn.Visible = false;

        MinWidth = ColumnWidth * ColumnsPerRow
                   + CmuPanelMetrics.RowSeparation * (ColumnsPerRow - 1)
                   + CmuPanelMetrics.PanelPaddingHorizontal * 2;

        _cornerTicks = CrtLobbyTheme.CornerTicks();
        Ground.AddChild(_cornerTicks);

        _shaderPass = new CrtScreenControl
        {
            // DefaultWindow's own BoxContainer, not one this window builds, so the raster covers the
            // title bar along with the body.
            Source = Children.OfType<BoxContainer>().First(),
            HorizontalExpand = true,
            VerticalExpand = true,
            Phosphor = StyleNano.CrtGreen,
            Intensity = ScanlineDepth,
            Curvature = 0f,
            Grain = false,
            Roll = false,
            ArtifactAmount = 0f,
        };
        AddChild(_shaderPass);

        ApplyTheme();

        _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    public void SetHuntVisible(bool visible) => _huntColumn.Visible = visible;

    private static BoxContainer ChoiceRow() => new()
    {
        Orientation = BoxContainer.LayoutOrientation.Horizontal,
        HorizontalExpand = true,
        VerticalExpand = true,
        SeparationOverride = CmuPanelMetrics.RowSeparation,
    };


    private Button BuildColumn(Control row, string buttonKey, string descKey, CmuChoiceCard.Palette palette)
    {
        var description = new RichTextLabel
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            MaxWidth = ColumnWidth - CmuPanelMetrics.ContentPaddingHorizontal * 2,
            Margin = CmuPanelMetrics.ContentPadding,
        };

        if (StyleNano.CrtUiEnabled)
            description.AddStyleClass(StyleNano.StyleClassCrtProseText);

        description.SetMessage(Loc.GetString(descKey), defaultColor: palette.Text.WithAlpha(0.85f));

        var button = new Button
        {
            Text = Loc.GetString(buttonKey),
            MinHeight = CmuPanelMetrics.RowTall,
            HorizontalExpand = true,
        };

        button.Label.HorizontalExpand = true;
        button.Label.Align = Label.AlignMode.Center;

        var column = new PanelContainer
        {
            MinWidth = ColumnWidth,
            VerticalExpand = true,
            Children =
            {
                new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    SeparationOverride = 0,
                    HorizontalExpand = true,
                    VerticalExpand = true,
                    Children = { description, button },
                },
            },
        };

        row.AddChild(column);
        _columns.Add((column, button, palette));
        StyleColumn(column, button, palette);

        return button;
    }

    private void StyleColumn(PanelContainer column, Button button, CmuChoiceCard.Palette palette)
    {
        column.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Fill,
            BorderColor = palette.Edge,
            BorderThickness = new Thickness(1),
        };

        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Button,
            BorderColor = palette.Edge,
            BorderThickness = new Thickness(0, 1, 0, 0),
            ContentMarginTopOverride = 8,
            ContentMarginBottomOverride = 8,
        };
        button.Label.FontColorOverride = palette.Text;
        button.Label.FontOverride = StyleNano.CrtUiEnabled
            ? StyleNano.GetCrtFont(_resourceCache, ButtonTextSize)
            : null;
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    private void OnCrtUiEnabledChanged(bool _)
    {
        ApplyTheme();
    }

    private void OnCrtUiColorChanged(string _)
    {
        ApplyTheme();
    }

    private void ApplyTheme()
    {
        Stylesheet = _stylesheetManager.SheetNano;

        var crt = StyleNano.CrtUiEnabled;
        var header = FindControl<PanelContainer>("WindowHeader");
        var titleLabel = FindControl<Label>("TitleLabel");
        var closeButton = FindControl<TextureButton>("CloseButton");

        if (crt)
        {
            AddStyleClass(StyleNano.StyleClassCrtWindow);

            header.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CrtTerminalPalette.Surface2,
                BorderColor = CrtTerminalPalette.Line,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 5,
                ContentMarginRightOverride = 6,
            };

            titleLabel.FontOverride = StyleNano.GetCrtFont(_resourceCache, TitleSize);
            titleLabel.FontColorOverride = CrtTerminalPalette.TextBright;
            closeButton.Modulate = CrtTerminalPalette.TextDim;

            // Full bleed: the header's rule and Ground's own run edge to edge.
            Contents.Margin = new Thickness(0);

            Ground.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CrtTerminalPalette.Surface0,
                BorderColor = CrtTerminalPalette.Line,
                BorderThickness = new Thickness(1, 0, 1, 1),
            };
        }
        else
        {
            RemoveStyleClass(StyleNano.StyleClassCrtWindow);
            header.PanelOverride = null;
            titleLabel.FontOverride = null;
            titleLabel.FontColorOverride = null;
            closeButton.Modulate = Color.White;
            Contents.Margin = new Thickness(10);
            Ground.PanelOverride = null;
        }

        _shaderPass.Visible = crt;
        _cornerTicks.Visible = crt;

        foreach (var (column, button, palette) in _columns)
            StyleColumn(column, button, palette);
    }
}
