using Content.Client.CMU14.Interface;
using Content.Client.CMU14.UserInterface.Options;
using Content.Client.CMU14.UserInterface.Options.Tabs;
using Content.Client.Administration.Managers;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : DefaultWindow
    {
        [Dependency] private IClientAdminManager _adminManager = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IStylesheetManager _stylesheetManager = default!;

        private readonly CmuOptionsFilter _filter;

        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _filter = new CmuOptionsFilter(Tabs);
            FilterBox.OnTextChanged += args => UpdateFilterCount(_filter.Apply(args.Text));

            ApplyCrtPalette();

            Tabs.SetTabTitle(0, Loc.GetString("cmu-ui-options-tab-gameplay"));
            Tabs.SetTabTitle(1, Loc.GetString("cmu-ui-options-tab-interface"));
            Tabs.SetTabTitle(2, Loc.GetString("cmu-ui-options-tab-chat"));
            Tabs.SetTabTitle(3, Loc.GetString("ui-options-tab-audio"));
            Tabs.SetTabTitle(4, Loc.GetString("cmu-ui-options-tab-video"));
            Tabs.SetTabTitle(5, Loc.GetString("ui-options-tab-accessibility"));
            Tabs.SetTabTitle(6, Loc.GetString("ui-options-tab-controls"));
            Tabs.SetTabTitle(7, Loc.GetString("ui-options-tab-admin"));

            InterfaceTab.CrtUiPreviewChanged += OnCrtUiPreviewChanged;
            InterfaceTab.OpenUiSetupRequested += OpenUiSetup; // CMU14: entry moved off the retired CmuTab
            OnClose += ResetCrtUiPreview;
            OnClose += ClearFilter;
            UpdateTabs();
            _stylesheetManager.CrtThemeChanged += ApplyCrtPalette;

            SetUpCrtScreen();
            _cfg.OnValueChanged(CCVars.CMUCrtMenuEffect, OnMenuEffectChanged);
        }

        /// <summary>
        ///     The surface texture only - scanlines and grain. No bulge, no roll bar, and a much
        ///     weaker vignette than the prop terminal uses: this is a page of settings being read,
        ///     not a piece of set dressing. Pitch, grain and intensity still come from the shared
        ///     cvars, so tuning those moves both.
        /// </summary>
        private void SetUpCrtScreen()
        {
            CrtOverlay.Source = CrtContent;
            CrtOverlay.Phosphor = CrtTerminalPalette.Accent;
            CrtOverlay.Curvature = 0f;
            CrtOverlay.Vignette = 0.12f;
            CrtOverlay.Roll = false;
            CrtOverlay.Visible = _cfg.GetCVar(CCVars.CMUCrtMenuEffect) && StyleNano.CrtUiEnabled;
        }

        private void OnMenuEffectChanged(bool _)
        {
            SetUpCrtScreen();
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _stylesheetManager.CrtThemeChanged -= ApplyCrtPalette;
            _cfg.UnsubValueChanged(CCVars.CMUCrtMenuEffect, OnMenuEffectChanged);
            InterfaceTab.CrtUiPreviewChanged -= OnCrtUiPreviewChanged;
            InterfaceTab.OpenUiSetupRequested -= OpenUiSetup;
            OnClose -= ResetCrtUiPreview;
            OnClose -= ClearFilter;
            ResetCrtUiPreview();
        }

        private void OpenUiSetup()
        {
            Close();
            new CmuUiSetupWindow().OpenCentered();
        }

        private void OnCrtUiPreviewChanged(bool enabled, string color)
        {
            _stylesheetManager.PreviewCrtUi(enabled, color);
        }

        private void ResetCrtUiPreview()
        {
            _stylesheetManager.ResetCrtUiPreview();
        }

        private void ApplyCrtPalette()
        {
            Stylesheet = _stylesheetManager.SheetNano;
            CrtLobbyTheme.ApplyWindow(this, useCrtTypography: false);

            // After the walk, never before.
            CmuOptionSection.RestyleAll(this);
            CmuOptionsLook.Apply(this);
            StyleFilterBar();
            SetUpCrtScreen();
        }

        private void StyleFilterBar()
        {
            FilterBar.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CrtTerminalPalette.Surface1,
                BorderColor = CrtTerminalPalette.Line,
                BorderThickness = new Thickness(0, 0, 0, 1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
            };

            FilterCount.FontColorOverride = CrtTerminalPalette.TextDim;
        }

        private void ClearFilter()
        {
            FilterBox.Text = string.Empty;
            _filter.Clear();
        }

        private void UpdateFilterCount(int count)
        {
            // Only while searching - the total on its own told the player nothing.
            FilterCount.Visible = !string.IsNullOrWhiteSpace(FilterBox.Text);
            if (!FilterCount.Visible)
                return;

            FilterCount.Text = count == 0
                ? Loc.GetString("cmu-ui-options-filter-none")
                : Loc.GetString("cmu-ui-options-filter-matches", ("count", count));
        }

        public void UpdateTabs()
        {
            ClearFilter();

            var isAdmin = _adminManager.IsAdmin(true);
            Tabs.SetTabVisible(7, isAdmin);

            GameplayTab.Control.ReloadValues();
            InterfaceTab.Control.ReloadValues();
            ChatTab.Control.ReloadValues();
            AudioTab.Control.ReloadValues();
            GraphicsTab.Control.ReloadValues();
            AccessibilityTab.Control.ReloadValues();
            AdminOptionsTab.Control.ReloadValues();

            UpdateFilterCount(0);
        }
    }
}
