using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.AlertLevel; // CMU14: admin tablet alert level control
using Content.Shared._RMC14.Marines.Announce; // CMU14: admin tablet faction toggle
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Marines.Announce;

[GenerateTypedNameReferences]
public sealed partial class MarineCommunicationsComputerWindow : FancyWindow
{
    // CMU14: admin tablet alert level control; the label polls the shared alert level like the wall displays do
    [Dependency] private IEntityManager _entMan = default!;
    private RMCAlertLevelSystem? _alertLevel; // CMU14
    private RMCAlertLevels _lastAlert = (RMCAlertLevels) (-1); // CMU14
    private string? _lastFaction; // CMU14
    public EntityUid? Tablet; // CMU14

    public MarineCommunicationsComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // CMU14
    }

    protected override void FrameUpdate(FrameEventArgs args) // CMU14 Method
    {
        base.FrameUpdate(args);
        if (!AdminSection.Visible)
            return;

        _alertLevel ??= _entMan.System<RMCAlertLevelSystem>();
        var current = _alertLevel.Get(Tablet) ?? RMCAlertLevels.Green;
        if (current != _lastAlert)
        {
            _lastAlert = current;
            var name = Loc.GetString($"rmc-alert-{current.ToString().ToLowerInvariant()}");
            AlertLevelCurrent.Text = $"{Loc.GetString("rmc-alert-level")}: {name}";
        }

        if (Tablet is { } tablet &&
            _entMan.TryGetComponent(tablet, out MarineCommunicationsComputerComponent? comms) &&
            comms.Faction != _lastFaction)
        {
            _lastFaction = comms.Faction;
            var target = comms.Faction == "opfor" ? Loc.GetString("cmu-fof-side-govfor") : Loc.GetString("cmu-fof-side-opfor");
            TabletFactionButton.Text = Loc.GetString("cmu-admin-tablet-faction-switch", ("faction", target));
        }
    }
}
