using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ColorNaming;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client.CMU14.UserInterface.ColorPicker;

/// <summary>
///     A colour option row: a label, then a dropdown-style button with a swatch and the colour's
///     name. The picking surface expands underneath it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CmuColorPicker : Control
{
    [Dependency] private readonly ILocalizationManager _localization = default!;

    private Color _color = Color.White;
    private string? _paletteId;

    /// <summary>
    ///     The row's label, e.g. "Highlight color".
    /// </summary>
    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    /// <summary>
    ///     Id of a <c>palette</c> prototype whose colours are offered as presets.
    /// </summary>
    public string? PaletteId
    {
        get => _paletteId;
        set
        {
            _paletteId = value;
            Panel.SetPalette(value);
        }
    }

    public Color Color
    {
        get => _color;
        set
        {
            _color = value;
            Panel.Color = value;
            UpdateDisplay();
        }
    }

    public event Action<Color>? OnColorChanged;

    public CmuColorPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Panel.OnColorPicked += color =>
        {
            _color = color;
            UpdateDisplay();
            OnColorChanged?.Invoke(color);
        };

        SwatchButton.OnPressed += _ => Panel.Visible = !Panel.Visible;

        UpdateDisplay();
    }

    private void UpdateDisplay()
    {
        Swatch.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = _color,
            // Deliberately not a palette colour: this border frames whatever the player picked, and
            // a CRT green baked in here would go stale when they change the theme colour.
            BorderColor = Color.White.WithAlpha(0.35f),
            BorderThickness = new Thickness(1),
        };

        // The name keeps the button's own text colour: the swatch already carries the picked colour,
        // and a dark pick would be unreadable as text.
        var name = ColorNaming.Describe(_color, _localization);
        NameLabel.Text = name.Length > 0 ? name.Substring(0, 1).ToUpperInvariant() + name.Substring(1) : name;
    }
}
