- type: antagSpecifier
  id: Cannibal
  prefRoles: [ CannibalRole ]
  jobBlacklistGroup:
  - AllGovforCommandStaff
  - AllOpforCommandStaff
  - AllCLFJobs
  briefing:
    text: cannibal-role-greeting
    color: DarkRed
    sound: "/Audio/Ambience/Antag/headrev_start.ogg"
  startingGear: AU14GearCannibal
  components:
  - type: Cannibal
  mindRoles:
  - MindRoleCannibal

- type: entity
  id: Cannibal
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: CannibalRule
  - type: AntagSelection
    selectionTime: JobsAssigned
    antags:
    - !type:FixedAntagCount
      proto: Cannibal

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCannibal
  name: Cannibal Mind Role
  components:
  - type: MindRole
    antagPrototype: CannibalRole
    exclusiveAntag: true
    roleType: SoloAntagonist

- type: antag
  parent: CMUAntagColonyBase
  id: CannibalRole
  name: roles-antag-cannibal-name
  setPreference: true
  objective: roles-antag-cannibal-objective

- type: startingGear
  id: AU14GearCannibal
  equipment:
    pocket1: KitchenKnife
