- type: antagSpecifier
  id: CLFSleeperAgent
  prefRoles: [ CLFSleeperAgentRole ]
  jobWhitelist:
  - AU14JobGOVFORPlatOp
  - AU14JobGOVFORSquadSergeant
  - AU14JobGOVFORSectionSergeant
  - AU14JobGOVFORRadioTelephoneOperator
  - AU14JobGOVFORVehicleCommander
  - AU14JobGOVFORMilitaryPoliceMan
  - AU14JobGOVFORNurse
  - AU14JobGOVFOREngineeringTech
  - AU14JobGOVFORCombatCorrespondent
  - AU14JobOPFORPlatOp
  - AU14JobOPFORSquadSergeant
  - AU14JobOPFORSectionSergeant
  - AU14JobOPFORRadioTelephoneOperator
  - AU14JobOPFORVehicleCrewman
  - AU14JobOPFORMilitaryPoliceMan
  - AU14JobOPFORAuxTech
  - AU14JobOPFORSquadCombatTech
  briefing:
    text: clf-sleeper-agent-role-greeting
    color: OliveDrab
    sound: "/Audio/Ambience/Antag/headrev_start.ogg"
  components:
  - type: CLFSleeperAgent
  mindRoles:
  - MindRoleCLFSleeperAgent

- type: entity
  id: CLFSleeperAgent
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: CLFSleeperAgentRule
  - type: AntagSelection
    selectionTime: JobsAssigned
    antags:
    - !type:FixedAntagCount
      proto: CLFSleeperAgent

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCLFSleeperAgent
  name: CLF Sleeper Agent Mind Role
  components:
  - type: MindRole
    antagPrototype: CLFSleeperAgentRole
    exclusiveAntag: true
    roleType: SoloAntagonist

- type: antag
  parent: CMUAntagColonyBase
  id: CLFSleeperAgentRole
  name: roles-antag-clf-sleeper-agent-name
  setPreference: true
  objective: roles-antag-clf-sleeper-agent-objective
