- type: antagSpecifier
  id: CLFVeteran
  prefRoles: [ CLFVeteranRole ]
  jobBlacklistGroup:
  - AllGovforJobs
  - AllOpforJobs
  - AllCLFJobs
# - AllColonyDepartmentHeadJobs
  - AllSynthJobs
  briefing:
    text: clfveteran-role-greeting
    color: OliveDrab
    sound: "/Audio/Ambience/Antag/headrev_start.ogg"
  startingGear: AU14GearCLFVeteran
  startingSkills:
  - type: RMCSkillFirearms
    level: 3
  - type: RMCSkillMeleeWeapons
    level: 3
  - type: RMCSkillCqc
    level: 3
  - type: RMCSkillEndurance
    level: 3
  - type: RMCSkillFireman
    level: 3
  - type: RMCSkillConstruction
    level: 3
  - type: RMCSkillLeadership
    level: 3
  - type: RMCSkillMedical
    level: 3
  - type: RMCSkillPolice
    level: 1
  - type: RMCSkillSurgery
    level: 3
  components:
  - type: CLFVeteran
  - type: ColonyBounty
    bounty: 1450
    reason: Known CLF insurgent - armed and dangerous
    recordName: CLF Veteran (Unknown)
    capturedFaxPaper: AUPaperCLFVeteranCaptured
  mindRoles:
  - MindRoleCLFVeteran

- type: entity
  id: CLFVeteran
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: CLFVeteranRule
  - type: AntagSelection
    selectionTime: JobsAssigned
    antags:
    - !type:FixedAntagCount
      proto: CLFVeteran

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleCLFVeteran
  name: CLF Veteran Mind Role
  components:
  - type: MindRole
    antagPrototype: CLFVeteranRole
    exclusiveAntag: true
    roleType: SoloAntagonist

- type: antag
  parent: CMUAntagColonyBase
  id: CLFVeteranRole
  name: roles-antag-clfveteran-name
  setPreference: true
  objective: roles-antag-clfveteran-objective

- type: startingGear
  id: AU14GearCLFVeteran
  equipment:
    suitstorage: AU14WeaponRevolverM44Inscribed
