- type: antagSpecifier
  id: SerialKiller
  prefRoles: [ SerialKillerRole ]
  jobBlacklistGroup:
  - AllGovforJobs
  - AllOpforJobs
  - AllCLFJobs
# - AllColonyDepartmentHeadJobs
  - AllSynthJobs
  briefing:
    text: serialkiller-role-greeting
    color: DarkRed
    sound: "/Audio/Ambience/Antag/headrev_start.ogg"
  components:
  - type: SerialKiller
  - type: ColonyBounty
    bounty: 2250
    reason: Wanted for multiple homicides - suspect at large
    recordName: Serial Killer (Unknown)
    includePrints: true
    capturedFaxPaper: AUPaperSerialKillerCaptured
  mindRoles:
  - MindRoleSerialKiller

- type: entity
  id: SerialKiller
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: SerialKillerRule
  - type: AntagSelection
    selectionTime: JobsAssigned
    antags:
    - !type:FixedAntagCount
      proto: SerialKiller

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSerialKiller
  name: Serial Killer Mind Role
  components:
  - type: MindRole
    antagPrototype: SerialKillerRole
    exclusiveAntag: true
    roleType: SoloAntagonist

- type: antag
  parent: CMUAntagColonyBase
  id: SerialKillerRole
  name: roles-antag-serialkiller-name
  setPreference: true
  objective: roles-antag-serialkiller-objective
