using Content.Client.Stylesheets;
using Robust.Client.ResourceManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private IResourceCache _resourceCache = default!;

    public Button CharacterSetupButton => CharacterSetup;

    /// <summary>The dotted run between the name and its tag; CmuLobbyLook gives it its stylebox.</summary>
    public PanelContainer HeadLeaderPanel => HeadLeader;
    public Button PrevCharacterButton => PrevCharButton;
    public Button NextCharacterButton => NextCharButton;
    public Button IgnoreAllegianceToggle => IgnoreAllegianceButton;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RefreshTheme();

        UpdateIgnoreAllegianceText(IgnoreAllegianceButton.Pressed);
        IgnoreAllegianceButton.OnToggled += args => UpdateIgnoreAllegianceText(args.Pressed);
    }

    public void RefreshTheme()
    {
        // The CRT theme styles every button label at one size via a stylesheet rule. FontOverride
        // is the reliable way to make just this one bigger - another style class would tie with
        // that rule on specificity.
        IgnoreAllegianceButton.Label.FontOverride = StyleNano.CrtUiEnabled
            ? StyleNano.GetCrtFont(_resourceCache, 10)
            : null;

        // Base menu only: toggled on turns the button solid red. The default Pressed state for a
        // plain Button is a thin highlighted border, easy to miss at a glance for something that
        // changes spawn behaviour. The CRT theme already themes every button consistently through
        // CrtButton, so this is left alone there.
        if (!StyleNano.CrtUiEnabled)
            IgnoreAllegianceButton.AddStyleClass(StyleNano.StyleClassButtonToggleRed);
        else
            IgnoreAllegianceButton.RemoveStyleClass(StyleNano.StyleClassButtonToggleRed);
    }

    private void UpdateIgnoreAllegianceText(bool pressed)
    {
        IgnoreAllegianceButton.Text = Loc.GetString(pressed
            ? "lobby-character-preview-ignore-allegiance-on"
            : "lobby-character-preview-ignore-allegiance-off");
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;

        HeadRow.Visible = value;
        HeadRule.Visible = value;
    }

    /// <summary>
    ///     Sets the page's head: the character's name as the big fact, and their pronoun and age as
    ///     the tag beside it. The name is plain text because it is one value at heading size; the tag
    ///     stays markup so the pronoun and the age keep their own colours.
    /// </summary>
    public void SetSummaryText(string name, string ageMarkup)
    {
        SummaryName.Text = name;
        SetSummaryLine(SummaryAge, ageMarkup);
    }

    private static void SetSummaryLine(RichTextLabel label, string markup)
    {
        if (string.IsNullOrWhiteSpace(markup))
        {
            label.SetMessage(FormattedMessage.Empty);
            label.Visible = false;
            return;
        }

        label.SetMessage(FormattedMessage.FromMarkupOrThrow(markup));
        label.Visible = true;
    }

    public void SetJobText(string value)
    {
        JobSummary.Text = value;
        JobSummary.Visible = !string.IsNullOrWhiteSpace(value);
    }

    public void SetSprite(EntityUid uid)
    {
        ProfilePreviewSpriteView.ClearPreview();
        ProfilePreviewSpriteView.PreviewDummy = uid;
        ProfilePreviewSpriteView.SetEntity(uid);
    }
}
