using System;
using System.Linq;
using Content.Client.CMU14.Interface;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Administration.Managers;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ObserveWarningWindow : DefaultWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private ISharedAdminManager _adminManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IStylesheetManager _stylesheetManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    private const int TitleSize = 8;

    private const int QuestionSize = 9;

    private const float ScanlineDepth = 0.9f;

    private CrtScreenControl _shaderPass = default!;
    private Control _cornerTicks = default!;

    public ObserveWarningWindow()
    {
        Title = Loc.GetString("observe-warning-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _cornerTicks = CrtLobbyTheme.CornerTicks();
        Ground.AddChild(_cornerTicks);

        _shaderPass = new CrtScreenControl
        {
            // DefaultWindow's own BoxContainer, so the raster covers the title bar along with the body.
            Source = Children.OfType<BoxContainer>().First(),
            HorizontalExpand = true,
            VerticalExpand = true,
            Phosphor = StyleNano.CrtGreen,
            Intensity = ScanlineDepth,
            Curvature = 0f,
            Grain = false,
            Roll = false,
            ArtifactAmount = 0f,
        };
        AddChild(_shaderPass);

        ApplyTheme();

        var player = _playerManager.LocalSession;

        if (player != null && _adminManager.IsAdmin(player))
        {
            ObserveButton.Text = Loc.GetString("observe-as-player");
            ObserveAsAdminButton.Visible = true;
            ObserveAsAdminButton.OnPressed += _ => { this.Close(); };
        }

        ObserveButton.OnPressed += _ => { this.Close(); };
        NevermindButton.OnPressed += _ => { this.Close(); };
        _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }


    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    private void OnCrtUiEnabledChanged(bool _)
    {
        ApplyTheme();
    }

    private void OnCrtUiColorChanged(string _)
    {
        ApplyTheme();
    }

    private void ApplyTheme()
    {
        Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.Apply(this);

        var crt = StyleNano.CrtUiEnabled;
        var header = FindControl<PanelContainer>("WindowHeader");
        var titleLabel = FindControl<Label>("TitleLabel");
        var closeButton = FindControl<TextureButton>("CloseButton");

        if (crt)
        {
            AddStyleClass(StyleNano.StyleClassCrtWindow);

            header.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CrtTerminalPalette.Surface2,
                BorderColor = CrtTerminalPalette.Line,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 5,
                ContentMarginRightOverride = 6,
            };

            titleLabel.FontOverride = StyleNano.GetCrtFont(_resourceCache, TitleSize);
            titleLabel.FontColorOverride = CrtTerminalPalette.TextBright;
            closeButton.Modulate = CrtTerminalPalette.TextDim;

            // Full bleed: the header's rule and Ground's own run edge to edge.
            Contents.Margin = new Thickness(0);

            Ground.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CrtTerminalPalette.Surface0,
                BorderColor = CrtTerminalPalette.Line,
                BorderThickness = new Thickness(1, 0, 1, 1),
            };

            Question.FontOverride = StyleNano.GetCrtFont(_resourceCache, QuestionSize);
            Question.FontColorOverride = CrtTerminalPalette.TextBright;
        }
        else
        {
            RemoveStyleClass(StyleNano.StyleClassCrtWindow);
            header.PanelOverride = null;
            titleLabel.FontOverride = null;
            titleLabel.FontColorOverride = null;
            closeButton.Modulate = Color.White;
            Contents.Margin = new Thickness(10);
            Ground.PanelOverride = null;
            Question.FontOverride = null;
            Question.FontColorOverride = null;
        }

        _shaderPass.Visible = crt;
        _cornerTicks.Visible = crt;

        // After the CrtLobbyTheme walk, never before: that walk hands every button the shared box.
        ApplyButtonColors();
    }

    private void ApplyButtonColors()
    {
        CmuButtonStyles.Apply(ObserveButton, CmuButtonStyles.Variant.Caution);
        CmuButtonStyles.Apply(ObserveAsAdminButton, CmuButtonStyles.Variant.Danger);
        CmuButtonStyles.Apply(NevermindButton, CmuButtonStyles.Variant.Neutral);
    }
}
