- type: entity
  parent: AdminObserver
  id: RMCAdminObserver
  categories: [ HideSpawnMenu ]
  components:
  - type: PropCaller
  - type: Language # CMU14: aghosts must speak any language over phones and radios
    defaultLanguage: English
  - type: AllLanguages
  - type: Loadout
    prototypes: [ RMCMobAghostGear ]
  - type: IntrinsicUI
    uis: { }

- type: startingGear
  parent: MobAghostGear
  id: RMCMobAghostGear # CMU14
  equipment:
    back: ClothingBackpackSatchelHolding
    id: RMCAdminPDA
  storage:
    back:
    - CMUAdminAccessConfigurator
    - HandheldHealthAnalyzer
    - CMHealthAnalyzer
    - DoorRemoteAll
    - AdminHypo
    - MeleeDebug200
    - MeleeDebugGibInsane
    - CMUDebugLightningStick
#   - ToolDebug
    - AU14MaintenanceJackSpecialAdmin
#   - AU14TabletGovfor #CMU14
    - CMUTabletGovforAdmin
#   - AU14TabletOpfor
    - CMUTabletOpforAdmin
    - RMCWelderAdmin
    - CMMultitool
    - CMTRayScanner
    - CMUAtmosScanner
    - HolofanProjectorDebug
