using Content.Client._RMC14.LinkAccount;
using Content.Shared._RMC14.CCVar;
using Content.Shared.CCVar;
using Content.Client.Options.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.UserInterface.Options.Tabs;

/// <summary>
///     Everything about the chat window and the text above people's heads.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ChatTab : Control
{
    [Dependency] private LinkAccountManager _linkAccount = default!;

    public ChatTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Channel can be null in replays.
        ShowOocPatronColor.Visible = _linkAccount.Tier != null;

        Control.AddOptionCheckBox(CCVars.CMUChatReadableFont, ChatReadableFontCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatEnableColorName, EnableColorNameCheckBox);

        // Off first, unlike the tint below: normal size is the default and the list reads as strength.
        Control.AddOptionDropDown(
            CCVars.CMUChatBigFont,
            ChatBigFontDropDown,
            [
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatBigFontOff,
                    Loc.GetString("ui-options-crt-chat-big-font-off")),
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatBigFontOne,
                    Loc.GetString("ui-options-crt-chat-big-font-one")),
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatBigFontTwo,
                    Loc.GetString("ui-options-crt-chat-big-font-two")),
            ]);

        // Muted first, because it is the default and the list reads as strength descending.
        Control.AddOptionDropDown(
            CCVars.CMUChatRowTint,
            ChatRowTintDropDown,
            [
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatRowTintMuted,
                    Loc.GetString("ui-options-crt-chat-row-tint-muted")),
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatRowTintFull,
                    Loc.GetString("ui-options-crt-chat-row-tint-full")),
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatRowTintOff,
                    Loc.GetString("ui-options-crt-chat-row-tint-off")),
            ]);

        Control.AddOptionPercentSlider(CCVars.ChatWindowOpacity, ChatWindowOpacitySlider);

        Control.AddOptionCheckBox(CCVars.ChatEnableRunechatBubbles, RunechatSpeechBubblesCheckBox);
        Control.AddOptionCheckBox(CCVars.LoocAboveHeadShow, ShowLoocAboveHeadCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatEnableFancyBubbles, FancySpeechBubblesCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatFancyNameBackground, FancyNameBackgroundsCheckBox);
        Control.AddOptionPercentSlider(CCVars.ChatRunechatBubbleScale, RunechatSpeechBubbleScaleSlider, 0.5f, 2f);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleTextOpacity, SpeechBubbleTextOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleSpeakerOpacity, SpeechBubbleSpeakerOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleBackgroundOpacity, SpeechBubbleBackgroundOpacitySlider);

        Control.AddOptionCheckBox(CCVars.ShowOocPatronColor, ShowOocPatronColor);
        Control.AddOptionCheckBox(RMCCVars.RMCChatSquadColorMode, RMCChatSquadColorModeCheckBox); // RMC14

        Control.AddOptionCheckBox(CCVars.ExamineLogInChat, ExamineLogInChatCheckBox);
        Control.AddOptionCheckBox(CCVars.ExamineFullTextInChat, ExamineFullTextInChatCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatGhostFollowButton, ChatGhostFollowButton);

        Control.AddOptionCheckBox(CCVars.ChatAutoFillHighlights, AutoFillHighlightsCheckBox);
        Control.AddOptionColorSlider(CCVars.ChatHighlightsColor, HighlightsColorSlider);

        Control.Initialize();
    }
}
