using Content.Shared.CMU14.Medical.Core;
using Content.Shared._RMC14.CCVar;
using Content.Shared._RMC14.NightVision;
using Content.Shared.CCVar;
using Content.Client.Options.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.UserInterface.Options.Tabs;

/// <summary>
///     Settings that change how you play rather than how the game looks or sounds.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GameplayTab : Control
{
    public GameplayTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var xenoNightVisionEntries = new List<OptionDropDownCVar<int>.ValueOption>
        {
            new((int) NightVisionState.Off, Loc.GetString("rmc-ui-xeno-night-vision-default-off")),
            new((int) NightVisionState.Half, Loc.GetString("rmc-ui-xeno-night-vision-default-half")),
            new((int) NightVisionState.Full, Loc.GetString("rmc-ui-xeno-night-vision-default-full")),
        };

        var constructionModeEntries = new List<OptionDropDownCVar<bool>.ValueOption>
        {
            new(true, Loc.GetString("cmu-ui-options-construction-mode-improved")),
            new(false, Loc.GetString("cmu-ui-options-construction-mode-default")),
        };

        Control.AddOptionCheckBox(RMCCVars.RMCAutoEjectMagazines, RMCAutoEjectMagazines);
        Control.AddOptionCheckBox(RMCCVars.RMCDamageYourself, RMCDamageYourself);

        Control.AddOptionCheckBox(CMUMedicalCCVars.TargetedHealingEnabled, TargetedHealingCheckBox);
        Control.AddOptionCheckBox(CMUMedicalCCVars.AutoReapplyKitsEnabled, AutoReapplyKitsCheckBox);
        Control.AddOptionCheckBox(CMUMedicalCCVars.UiLessSurgeryEnabled, UiLessSurgeryCheckBox);

        Control.AddOptionCheckBox(RMCCVars.RMCXenoAbilityPreviews, XenoAbilityPreviewsCheckBox);
        Control.AddOptionDropDown(RMCCVars.RMCXenoDefaultNightVision, RMCXenoNightVisionDefault, xenoNightVisionEntries);

        Control.AddOptionCheckBox(CCVars.CMUScreamOnHotbarEnabled, ScreamOnHotbarCheckBox);
        Control.AddOptionCheckBox(RMCCVars.RMCAutoPunctuate, RMCAutoPunctuate);

        Control.AddOptionDropDown(CCVars.ConstructionMenuImproved, DropDownConstructionMode, constructionModeEntries);

        Control.Initialize();
    }
}
