using System.Linq;
using Content.Client.UserInterface.Screens;
using Content.Shared._RMC14.CCVar;
using Content.Shared.CCVar;
using Content.Shared.HUD;
using Content.Client.Options.UI;
using Content.Client.CMU14.Interface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.CMU14.UserInterface.Options.Tabs;

/// <summary>
///     How the game is laid out on screen - HUD, viewport arrangement, storage windows and the CRT
///     theme.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class InterfaceTab : Control
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public event Action<bool, string>? CrtUiPreviewChanged;

    public event Action? OpenUiSetupRequested;

    public InterfaceTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        OpenUiSetupButton.OnPressed += _ => OpenUiSetupRequested?.Invoke();

        var themes = _prototypeManager.EnumeratePrototypes<HudThemePrototype>().ToList();
        themes.Sort();
        var themeEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var theme in themes)
        {
            themeEntries.Add(new OptionDropDownCVar<string>.ValueOption(theme.ID, Loc.GetString(theme.Name)));
        }

        var layoutEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var layout in Enum.GetValues(typeof(ScreenType)))
        {
            layoutEntries.Add(new OptionDropDownCVar<string>.ValueOption(
                layout.ToString()!,
                Loc.GetString($"ui-options-hud-layout-{layout.ToString()!.ToLower()}")));
        }

        var separatedHudStatusSideEntries = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new("right", Loc.GetString("au14-ui-options-separated-hud-status-side-right")),
            new("left", Loc.GetString("au14-ui-options-separated-hud-status-side-left")),
        };

        Control.AddOptionCheckBox(CCVars.HudHeldItemShow, ShowHeldItemCheckBox);
        Control.AddOptionCheckBox(CCVars.CombatModeIndicatorsPointShow, ShowCombatModeIndicatorsCheckBox);
        Control.AddOptionCheckBox(RMCCVars.RMCShowNewPlayerIcons, RMCShowNewPlayerIcons);
        Control.AddOptionDropDown(CVars.InterfaceTheme, DropDownHudTheme, themeEntries);
        Control.AddOptionDropDown(CCVars.UILayout, DropDownHudLayout, layoutEntries);

        // AU14: viewport centering for the Separated layout (chat panel otherwise pushes the view left).
        Control.AddOptionCheckBox(Content.Shared._AU14.CCVar.AU14CCVars.CenterSeparatedViewport, CenterSeparatedViewportCheckBox);
        Control.AddOptionDropDown(Content.Shared._AU14.CCVar.AU14CCVars.SeparatedHudStatusSide, SeparatedHudStatusSideDropdown, separatedHudStatusSideEntries);
        SeparatedLayoutOptions.DependOn(() =>
            DropDownHudLayout.Button.SelectedMetadata is string layout && layout == nameof(ScreenType.Separated));

        Control.AddOptionDropDown(CCVars.CMUChatHousing, ChatHousingDropDown,
        [
            new OptionDropDownCVar<string>.ValueOption(CmuHousingPalette.Off, Loc.GetString("cmu-ui-options-chat-housing-off")),
            new OptionDropDownCVar<string>.ValueOption("gunmetal", Loc.GetString("cmu-ui-options-chat-housing-gunmetal")),
            new OptionDropDownCVar<string>.ValueOption("olive", Loc.GetString("cmu-ui-options-chat-housing-olive")),
            new OptionDropDownCVar<string>.ValueOption("beige", Loc.GetString("cmu-ui-options-chat-housing-beige")),
        ]);
        Control.AddOptionDropDown(CCVars.CMUMenuBarStyle, MenuBarStyleDropDown,
        [
            new OptionDropDownCVar<string>.ValueOption(CCVars.CMUMenuBarStyleOutlined, Loc.GetString("cmu-ui-options-menu-bar-style-outlined")),
            new OptionDropDownCVar<string>.ValueOption(CCVars.CMUMenuBarStyleRaised, Loc.GetString("cmu-ui-options-menu-bar-style-raised")),
        ]);
        // The housing brings its own keycaps, so the key style only matters with it off.
        MenuBarStyleOptions.DependOn(() =>
            ChatHousingDropDown.Button.SelectedMetadata is string housing && housing == CmuHousingPalette.Off);

        Control.AddOptionCheckBox(CCVars.OpaqueStorageWindow, OpaqueStorageWindowCheckBox);
        Control.AddOptionCheckBox(CCVars.StaticStorageUI, StaticStorageUI);

        var crtUiEnabled = Control.AddOption(new OptionCrtUiEnabled(Control, _cfg, CrtUiEnabledCheckBox));
        crtUiEnabled.PreviewValueChanged += UpdateCrtUiOptionsPreview;
        Control.AddOptionCheckBox(CCVars.CMUVoteUiLarge, VoteUiLargeCheckBox);

        Control.AddOptionCheckBox(CVars.DiscordEnabled, DiscordRich);

        Control.Initialize();
    }

    private void UpdateCrtUiOptionsPreview()
    {
        // The colour picker is still switched off, so the preview reads the colour already in the cvar.
        CrtUiPreviewChanged?.Invoke(CrtUiEnabledCheckBox.Pressed, _cfg.GetCVar(CCVars.CrtUiColor));
    }

    /// <summary>
    ///     The CRT toggle, as a hand-written option so the window can repaint live instead of waiting
    ///     for Apply. Everything else on this tab is an ordinary <c>AddOptionCheckBox</c>.
    /// </summary>
    private sealed class OptionCrtUiEnabled : BaseOptionCVar<bool>
    {
        private readonly CheckBox _checkBox;
        private bool _suppressToggle;

        public event Action? PreviewValueChanged;

        protected override bool Value
        {
            get => _checkBox.Pressed;
            set
            {
                _suppressToggle = true;
                try
                {
                    _checkBox.Pressed = value;
                }
                finally
                {
                    _suppressToggle = false;
                }
            }
        }

        public OptionCrtUiEnabled(
            OptionsTabControlRow controller,
            IConfigurationManager cfg,
            CheckBox checkBox)
            : base(controller, cfg, CCVars.CrtUiEnabled)
        {
            _checkBox = checkBox;
            _checkBox.OnToggled += _ =>
            {
                if (_suppressToggle)
                    return;

                ValueChanged();
            };
        }

        public override void LoadValue()
        {
            base.LoadValue();
            NotifyPreviewValueChanged();
        }

        public override void SaveValue()
        {
            base.SaveValue();
            NotifyPreviewValueChanged();
        }

        public override void ResetToDefault()
        {
            base.ResetToDefault();
            NotifyPreviewValueChanged();
        }

        protected override void ValueChanged()
        {
            base.ValueChanged();
            NotifyPreviewValueChanged();
        }

        private void NotifyPreviewValueChanged()
        {
            PreviewValueChanged?.Invoke();
        }
    }
}
