- type: entity
  parent: AU14BaseMobSpeciesOrganicTDThirdparty
  id: CMUBaseMobSpeciesUPPLine
  abstract: true
  suffix: CMU, UPP, Line

- type: entity
  parent: AU14SquadTD
  id: CMUSquadUPPLine
  name: UPP Line
  components:
  - type: SquadTeam
    group: UPP Line
