using System.Linq;
using System.Numerics;
using Content.Client.CMU14.Interface;
using Content.Client.CMU14.UserInterface.Guidebook;
using Content.Client.Guidebook.RichText;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls.FancyTree;
using Content.Client.UserInterface.Systems.Info;
using Content.Shared.CCVar;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Configuration;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Guidebook.Controls;

[GenerateTypedNameReferences]
public sealed partial class GuidebookWindow : FancyWindow, ILinkClickHandler, IAnchorClickHandler
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private DocumentParsingManager _parsingMan = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IResourceManager _resourceManager = default!;
    [Dependency] private IStylesheetManager _stylesheetManager = default!;

    private Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> _entries = [];

    private readonly ISawmill _sawmill;
    private bool _subscribedToCvars;

    public ProtoId<GuideEntryPrototype>? Selected { get; private set; }


    // CMU: search, history and the section list.
    private readonly CmuGuideIndex _index;
    private readonly Dictionary<ProtoId<GuideEntryPrototype>, ProtoId<GuideEntryPrototype>> _parents = new();
    private readonly Stack<ProtoId<GuideEntryPrototype>> _back = new();
    private readonly Stack<ProtoId<GuideEntryPrototype>> _forward = new();
    private readonly List<Control> _sections = new();
    private bool _recordHistory = true;
    private int _pendingSection = -1;
    private bool _showingGuide;

    public GuidebookWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = Logger.GetSawmill("guidebook");
        _index = new CmuGuideIndex(_resourceManager);
        ApplyCrtPalette();

        Tree.OnSelectedItemChanged += OnSelectionChanged;
        TableOfContents.OnSelectedItemChanged += OnTableOfContentsSelectionChanged;

        SearchBar.OnTextChanged += _ =>
        {
            HandleFilter();
            UpdateResults();
        };

        BackButton.OnPressed += _ => GoBack();
        ForwardButton.OnPressed += _ => GoForward();
        HomeButton.OnPressed += _ => GoHome();

        _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _subscribedToCvars = true;
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        Shutdown();
        base.Dispose(disposing);
    }

    /// <summary>
    /// Unsubscribes callbacks owned by this window before it is removed from the UI tree.
    /// </summary>
    public void Shutdown()
    {
        if (!_subscribedToCvars)
            return;

        _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _subscribedToCvars = false;
    }

    private void OnCrtUiColorChanged(string _)
    {
        ApplyCrtPalette();
    }

    private void OnCrtUiEnabledChanged(bool _)
    {
        ApplyCrtPalette();
        CrtLobbyTheme.Apply(EntryContainer, useCrtTypography: false);
        CrtLobbyTheme.Apply(Tree, useCrtTypography: false);
    }

    private void ApplyCrtPalette()
    {
        ((Control) this).Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.Apply(this, useCrtTypography: false);
        CmuGuidebookLook.Apply(this);
    }

    public void HandleClick(string link)
    {
        if (!_entries.TryGetValue(link, out var entry))
            return;

        NavigateTo(entry.Id);
    }

    public void HandleAnchor(IPrototypeLinkControl prototypeLinkControl)
    {
        var prototype = prototypeLinkControl.LinkedPrototype;
        if (prototype == null)
            return;

        var (linkableControls, _) = GetLinkableControlsAndLinks(EntryContainer);
        foreach (var linkableControl in linkableControls)
        {
            if (linkableControl.RepresentedPrototype != prototype)
                continue;

            if (linkableControl is not Control control)
                return;

            // Check if the target item is currently filtered out
            if (!control.Visible)
                control.Visible = true;

            UserInterfaceManager.DeferAction(() => ScrollTo(control));

            break;
        }
    }

    private void OnSelectionChanged(TreeItem? item)
    {
        if (item != null && item.Metadata is GuideEntry entry)
        {
            // do nothing if the guide is the same as the currently selected one
            if (entry.Id == Selected)
                return;


            ShowGuide(entry);
        else
            ClearSelectedGuide();
    }

    private void OnTableOfContentsSelectionChanged(TreeItem? item)
    {
        if (item is null || item.Metadata is not Label entry)
            return;

        UserInterfaceManager.DeferAction(() =>
        {
            if (entry.GetControlScrollPosition() is not { } position)
                return;

            Scroll.HScrollTarget = position.X;
            Scroll.VScrollTarget = position.Y;
        });
    }

    public void ClearSelectedGuide()
    {
        Placeholder.Visible = true;
        EntryContainer.Visible = false;
        EntryContainer.RemoveAllChildren();

        Selected = null;
        Breadcrumb.Text = string.Empty;
        _sections.Clear();

    }

    private void ShowGuide(GuideEntry entry)
    {
        if (_recordHistory && LastEntry != default && LastEntry != entry.Id && _showingGuide)
        {
            _back.Push(LastEntry);
            _forward.Clear();
        }

        _showingGuide = true;
        Scroll.SetScrollValue(default);
        Placeholder.Visible = false;
        EntryContainer.Visible = true;
        EntryContainer.RemoveAllChildren();
        using var file = _resourceManager.ContentFileReadText(entry.Text);

        if (!_parsingMan.TryAddMarkup(EntryContainer, file.ReadToEnd()))
        {
            // The guidebook will automatically display the in-guidebook error if it fails

            _sawmill.Error($"Failed to parse contents of guide document {entry.Id}.");
        }

        CrtLobbyTheme.Apply(EntryContainer, useCrtTypography: false);

        Selected = entry.Id;
        LastEntry = entry.Id;
        ReturnContainer.Visible = entry.RuleEntry;

        CollectSections();
        UpdateBreadcrumb(entry);
        UpdateHistoryButtons();
        HandleFilter();

        var (linkableControls, linkControls) = GetLinkableControlsAndLinks(EntryContainer);

        HashSet<IPrototype> availablePrototypeLinks = [];
        foreach (var linkableControl in linkableControls)
        {
            var prototype = linkableControl.RepresentedPrototype;
            if (prototype != null)
                availablePrototypeLinks.Add(prototype);
        }

        foreach (var linkControl in linkControls)
        {
            var prototype = linkControl.LinkedPrototype;
            if (prototype != null && availablePrototypeLinks.Contains(prototype))
                linkControl.EnablePrototypeLink();
        }


        if (_pendingSection >= 0)
        {
            var section = _pendingSection;
            UserInterfaceManager.DeferAction(() => ScrollToSection(section));
        }

        _pendingSection = -1;

        RepopulateTableOfContents();
    }

    /// <summary>
    ///     CMU: moves to another entry, optionally to one of its headings, keeping the tree and history in step.
    /// </summary>
    private void NavigateTo(ProtoId<GuideEntryPrototype> id, int section = -1, bool record = true)
    {
        if (!_entries.TryGetValue(id, out var entry))
            return;

        _pendingSection = section;
        _recordHistory = record;

        try
        {
            if (Tree.TryGetIndexFromMetadata(entry, out var index) && Tree.SelectedIndex != index)
            {
                Tree.ExpandParentEntries(index.Value);
                Tree.SetSelectedIndex(index);
            }
            else
            {
                ShowGuide(entry);
            }
        }
        finally
        {
            _recordHistory = true;
        }
    }

    private void GoBack()
    {
        if (!_back.TryPop(out var previous))
            return;

        _forward.Push(LastEntry);
        NavigateTo(previous, record: false);
    }

    private void GoForward()
    {
        if (!_forward.TryPop(out var next))
            return;

        _back.Push(LastEntry);
        NavigateTo(next, record: false);
    }

    private void GoHome()
    {
        var rules = UserInterfaceManager.GetUIController<InfoUIController>().GetCoreRuleEntry();
        NavigateTo(rules.Id);
    }

    private void UpdateHistoryButtons()
    {
        BackButton.Disabled = _back.Count == 0;
        ForwardButton.Disabled = _forward.Count == 0;
    }

    private void UpdateBreadcrumb(GuideEntry entry)
    {
        var path = new List<string>();
        var id = entry.Id;

        for (var i = 0; i < 8; i++)
        {
            if (!_entries.TryGetValue(id, out var step))
                break;

            path.Insert(0, GetDisplayName(step));

            if (!_parents.TryGetValue(id, out var parent))
                break;

            id = parent;
        }

        Breadcrumb.Text = string.Join(" > ", path);
    }

    private void CollectSections()
    {
        _sections.Clear();
        CollectHeadings(EntryContainer);
    }

    private void CollectHeadings(Control parent)
    {
        foreach (var child in parent.Children)
        {
            if (child is Label label &&
                (label.HasStyleClass("LabelHeadingBigger") ||
                 label.HasStyleClass("LabelHeading") ||
                 label.HasStyleClass("LabelKeyText")))
            {
                _sections.Add(label);
            }

            if (child.ChildCount > 0)
                CollectHeadings(child);
        }
    }

    private void ScrollToSection(int section)
    {
        if (section >= 0 && section < _sections.Count)
            ScrollTo(_sections[section]);
    }

    private void ScrollTo(Control control)
    {
        if (control.GetControlScrollPosition() is not { } position)
            return;

        Scroll.HScrollTarget = position.X;
        Scroll.VScrollTarget = position.Y;
>>>>>>> crt-terminal-shader
    }

    private int? HeadingDepth(Label control)
    {
        if (control.StyleClasses.Contains("LabelHeadingBigger"))
            return 1;
        else if (control.StyleClasses.Contains("LabelHeading"))
            return 2;
        else if (control.StyleClasses.Contains("LabelKeyText"))
            return 3;

        return null;
    }

    private void RepopulateTableOfContents()
    {
        TableOfContents.Clear();

        var firstEntry = TableOfContents.AddItem(null);
        firstEntry.Label.Text = Loc.GetString("guidebook-toc-header");

        var labels = EntryContainer.GetControlOfType<Label>(true);
        var stack = new Stack<(TreeItem Item, int Depth)>();

        foreach (var label in labels)
        {
            if (HeadingDepth(label) is not { } depth)
                continue;

            while (stack.TryPeek(out var previous) && previous.Depth >= depth)
            {
                stack.Pop();
            }

            var item = stack.TryPeek(out var parent)
                ? TableOfContents.AddItem(parent.Item)
                : TableOfContents.AddItem(firstEntry);
            item.Label.Text = label.Text;
            item.Metadata = label;

            stack.Push((item, depth));
        }

        // Expand all entries, but collapse the first one
        TableOfContents.SetAllExpanded(true);
        firstEntry.SetExpanded(false);
        CrtLobbyTheme.Apply(TableOfContents, useCrtTypography: false);
    }

    /// <summary>
    /// Updates the guides used in the window.
    /// Returns whether the guides changed.
    /// </summary>
    public bool UpdateGuides(
        Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> entries,
        List<ProtoId<GuideEntryPrototype>>? rootEntries = null,
        ProtoId<GuideEntryPrototype>? forceRoot = null,
        ProtoId<GuideEntryPrototype>? selected = null)
    {
        // check if old and new entries are equal
        var sameAsLastUpdate = entries.Count != _entries.Count || !entries.All(_entries.Contains);
        if (sameAsLastUpdate)
        {
            _entries = entries;
            _index.SetEntries(entries);

            _parents.Clear();
            foreach (var entry in entries.Values)
            {
                foreach (var child in entry.Children)
                {
                    _parents[child] = entry.Id;
                }
            }

            _back.Clear();
            _forward.Clear();
            _showingGuide = false;
            SearchBar.Text = string.Empty;
            UpdateResults();

            RepopulateTree(rootEntries, forceRoot);
            ClearSelectedGuide();

            Split.State = SplitContainer.SplitState.Auto;
            if (entries.Count == 1)
            {
                TreeBox.Visible = false;
                Split.ResizeMode = SplitContainer.SplitResizeMode.NotResizable;
                selected = entries.Keys.First();
            }
            else
            {
                TreeBox.Visible = true;
                Split.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
            }
        }

        var item = selected == null
            ? null
            : Tree.Items.FirstOrDefault(x => x.Metadata is GuideEntry entry && entry.Id == selected);

        // CMU: the book always opens on a page. The first root is the rules overview, which is priority 0.
        item ??= Tree.Items.FirstOrDefault();

        if (item != null)
        {
            Tree.ExpandParentEntries(item.Index);
            Tree.SetSelectedIndex(item.Index);
        }

        UpdateHistoryButtons();

        return sameAsLastUpdate;
    }

    private IEnumerable<GuideEntry> GetSortedEntries(List<ProtoId<GuideEntryPrototype>>? rootEntries)
    {
        if (rootEntries == null)
        {
            HashSet<ProtoId<GuideEntryPrototype>> entries = [.. _entries.Keys];
            foreach (var entry in _entries.Values)
            {
                entries.ExceptWith(entry.Children);
            }

            rootEntries = [.. entries];
        }

        // Only roots need to be sorted.
        // As defined in the SS14 Dev Wiki, children are already sorted based on their child field order within their parent's prototype definition.
        // Roots are sorted by priority. If there is no defined priority for a root then it is by definition sorted undefined.
        return rootEntries
            .Select(rootEntryId => _entries[rootEntryId])
            .OrderBy(rootEntry => rootEntry.Priority)
            .ThenBy(GetDisplayName);
    }

    private string GetDisplayName(GuideEntry entry)
    {
        return _loc.TryGetString(entry.Name, out var name)
            ? name
            : entry.Name;
    }

    private void RepopulateTree(List<ProtoId<GuideEntryPrototype>>? roots = null,
        ProtoId<GuideEntryPrototype>? forcedRoot = null)
    {
        Tree.Clear();

        HashSet<ProtoId<GuideEntryPrototype>> addedEntries = [];

        var parent = forcedRoot == null ? null : AddEntry(forcedRoot.Value, null, addedEntries);
        foreach (var entry in GetSortedEntries(roots))
        {
            AddEntry(entry.Id, parent, addedEntries);
        }

        // CMU: the book is over a hundred entries, so it opens folded up; the open page's branch is expanded for it.
        Tree.SetAllExpanded(false);
        CrtLobbyTheme.Apply(Tree, useCrtTypography: false);

        foreach (var item in Tree.Items)
        {
            item.Button.RemoveStyleClass(StyleNano.StyleClassCrtButton);
            item.Button.AddStyleClass(StyleNano.StyleClassCmuGuideResult);
            item.Label.FontColorOverride = CmuGuidebookLook.Ink;
        }
    }

    private TreeItem? AddEntry(ProtoId<GuideEntryPrototype> id,
        TreeItem? parent,
        HashSet<ProtoId<GuideEntryPrototype>> addedEntries)
    {
        if (!_entries.TryGetValue(id, out var entry))
            return null;

        if (!addedEntries.Add(id))
        {
            // TODO GUIDEBOOK Maybe allow duplicate entries?
            // E.g., for adding medicine under both chemicals & the chemist job
            _sawmill.Error($"Adding duplicate guide entry: {id}");
            return null;
        }

        var rulesProto = UserInterfaceManager.GetUIController<InfoUIController>().GetCoreRuleEntry();
        if (entry.RuleEntry && entry.Id != rulesProto.Id)
            return null;

        var item = Tree.AddItem(parent);
        item.Metadata = entry;
        item.Label.Text = GetDisplayName(entry);

        foreach (var child in entry.Children)
        {
            AddEntry(child, item, addedEntries);
        }

        return item;
    }

    /// <summary>CMU: runs a search as though it had been typed into the box.</summary>
    public void Search(string query)
    {
        SearchBar.Text = query;
        HandleFilter();
        UpdateResults();
    }

    private void HandleFilter()
    {
        if (Tree.SelectedItem != null && Tree.SelectedItem.Metadata is GuideEntry entry && entry.FilterEnabled)
        {
            var foundElements = EntryContainer.GetSearchableControls();

            foreach (var element in foundElements)
            {
                element.SetHiddenState(true, SearchBar.Text.Trim());
            }
        }
    }

    private void UpdateResults()
    {
        var query = SearchBar.Text.Trim();
        Results.RemoveAllChildren();

        if (query.Length < 2)
        {
            Results.Visible = false;
            Tree.Visible = true;
            return;
        }

        Results.Visible = true;
        Tree.Visible = false;

        var hits = _index.Search(query, GetDisplayName);
        if (hits.Count == 0)
        {
            Results.AddChild(new Label
            {
                Text = Loc.GetString("cmu-guidebook-search-none"),
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4, 6, 0, 0),
            });
            return;
        }

        var titles = hits.Where(hit => hit.IsTitle).ToList();
        var pages = hits.Where(hit => !hit.IsTitle).ToList();

        if (titles.Count > 0)
        {
            Results.AddChild(Group("cmu-guidebook-search-titles"));
            foreach (var hit in titles)
            {
                Results.AddChild(new CmuGuideResult(hit, () => NavigateTo(hit.Entry.Id, hit.Section)));
            }
        }

        if (pages.Count > 0)
        {
            Results.AddChild(Group("cmu-guidebook-search-pages"));
            foreach (var hit in pages)
            {
                Results.AddChild(new CmuGuideResult(hit, () => NavigateTo(hit.Entry.Id, hit.Section)));
            }
        }
    }

    private static Label Group(string key)
    {
        return new Label
        {
            Text = Loc.GetString(key),
            StyleClasses = { "LabelSubText" },
            Margin = new Thickness(4, 8, 0, 2),
        };
    }

    private static (List<IPrototypeRepresentationControl>, List<IPrototypeLinkControl>) GetLinkableControlsAndLinks(Control parent)
    {
        List<IPrototypeRepresentationControl> linkableList = [];
        List<IPrototypeLinkControl> linkList = [];

        foreach (var child in parent.Children)
        {
            var hasChildren = child.ChildCount > 0;

            if (child is IPrototypeLinkControl linkChild)
                linkList.Add(linkChild);
            else if (child is IPrototypeRepresentationControl linkableChild)
                linkableList.Add(linkableChild);

            if (!hasChildren)
                continue;

            var (childLinkableList, childLinkList) = GetLinkableControlsAndLinks(child);

            linkableList.AddRange(childLinkableList);
            linkList.AddRange(childLinkList);
        }

        return (linkableList, linkList);
    }
}
