name: Testcases

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master, staging, stable ]

permissions:
  contents: read
  actions: write # required by artifacts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # cancel old, start anew in same PR

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Pull engine updates # version sync
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Update engine submodules
        run: cd RobustToolbox && git submodule update --init --recursive

      - uses: actions/setup-dotnet@v5 # cache lock files
        with:
          dotnet-version: 9.0.x
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/*.props
            **/*.targets
            **/packages.lock.json
      - run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration DebugOpt --no-restore --property:WarningLevel=0 /m # WarningLevel=0 turns off emission of all warning messages
      - name: Run Content.Tests # catch early fails
        run: dotnet test --no-build --verbosity normal --configuration DebugOpt Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0

      - name: Upload build artifacts # upload bin/ directory for shards
        uses: actions/upload-artifact@v7
        with:
          name: build-debugopt
          path: |
            bin/
            Content.IntegrationTests/
            RobustToolbox/
            Resources/
            *.sln
            **/*.csproj
            **/*.props
            **/*.targets
          if-no-files-found: error # detect empty artifact
          retention-days: 1

  # Split into 8 shards (10 total) for now, GH supports ~20 concurrent jobs
  # New test folders need to be declared (IMPORTANT) or it will silently not run
  # Catch-all guard will be made in future
  integration-tests:
    name: ${{ matrix.shard.name }}
    if: github.event.pull_request.draft == false
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # run all shards, even when one fails
      matrix:
        shard:
          - name: root # generated by bash script below (Content.IntegrationTests.Tests)

          # Legacy SS14 Tests - aach shard groups related namespaces
          # The contains (~) operator includes subfolders.
          - name: admin_access_ui
            filter: >-
              FullyQualifiedName~Content.IntegrationTests.Tests.Administration.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Access.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Commands.
              | FullyQualifiedName~Content.IntegrationTests.Tests.EncryptionKeys.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Lobby.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Roles.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Toolshed.
              | FullyQualifiedName~Content.IntegrationTests.Tests.UserInterface.

          - name: atmos_fluids_physics
            filter: >-
              FullyQualifiedName~Content.IntegrationTests.Tests.Atmos.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Explosion.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Fluids.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Gravity.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Physics.

          - name: mapping_station_shuttle_round
            filter: >-
              FullyQualifiedName~Content.IntegrationTests.Tests.GameRules.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Mapping.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Procedural.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Replays.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Round.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Shuttle.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Station.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Tiles.

          - name: cleanup_entities_world
            filter: >-
              FullyQualifiedName~Content.IntegrationTests.Tests.Cleanup.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Damageable.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Destructible.
              | FullyQualifiedName~Content.IntegrationTests.Tests.DeviceLinking.
              | FullyQualifiedName~Content.IntegrationTests.Tests.DeviceNetwork.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Disposal.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Doors.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Embedding.
              | FullyQualifiedName~Content.IntegrationTests.Tests.GameObjects.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Payload.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Power.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Weldable.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Wires.

          - name: gameplay_core
            filter: >-
              FullyQualifiedName~Content.IntegrationTests.Tests.Actions.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Body.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Buckle.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Chameleon.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Climbing.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Cloning.
              | FullyQualifiedName~Content.IntegrationTests.Tests.DoAfter.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Interaction.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Internals.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Minds.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Movement.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Networking.
              | FullyQualifiedName~Content.IntegrationTests.Tests.NPC.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Puller.

          - name: items_storage_crafting
            filter: >-
              FullyQualifiedName~Content.IntegrationTests.Tests.Chemistry.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Construction.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Hands.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Lathe.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Materials.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Sprite.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Storage.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Strip.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Tag.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Utility.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Vending.

          - name: proto_lint_localization_serialization
            filter: >-
              FullyQualifiedName~Content.IntegrationTests.Tests.Guidebook.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Linter.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Localization.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Preferences.
              | FullyQualifiedName~Content.IntegrationTests.Tests.PrototypeTests.
              | FullyQualifiedName~Content.IntegrationTests.Tests.Serialization.

          # CMU Tests
          - name: cmu_rmc
            filter: >-
              FullyQualifiedName~Content.IntegrationTests._CMU14.
              | FullyQualifiedName~Content.IntegrationTests._RMC14.

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: Content.IntegrationTests

      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: build-debugopt
          path: .

      - name: Verify integration test artifact
        run: |
          set -euo pipefail
          TEST_DLL=$(find bin -name "Content.IntegrationTests.dll" | head -1)
          if [ -z "$TEST_DLL" ]; then
            echo "Content.IntegrationTests.dll was not found!"
            exit 1
          fi
          echo "found test artifact:"
          ls -lh "$TEST_DLL"

      - name: Prepare runtime content
        run: |
          cp -r Resources bin/Content.IntegrationTests/
          cp -r RobustToolbox/Resources bin/Content.IntegrationTests/

      - name: Verify runtime content
        run: |
          echo "--- areas_fiorina.rsi locations ---"
          find . -path "*/areas_fiorina.rsi" -type d
          echo "--- bin/Content.IntegrationTests/ top-level ---"
          ls -la bin/Content.IntegrationTests/

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Run ${{matrix.shard.name}}
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: |
          $env:DOTNET_gcServer = 1

          if ("${{matrix.shard.name}}" -eq "root") {
            $files = Get-ChildItem -Path "Content.IntegrationTests/Tests" -Filter "*.cs" |
                     Select-Object -ExpandProperty BaseName
            if (-not $files) {
              Write-Error "${{matrix.shard.name}} shard: no test files found in Content.IntegrationTests/Tests!"
              exit 1
            }
          $FILTER = ($files | ForEach-Object {
            "FullyQualifiedName~Content.IntegrationTests.Tests.$_"
          }) -join " | "
          } else {
            $FILTER = '${{matrix.shard.filter}}'
          }

          Write-Host "${{matrix.shard.name}} shard is using the following filter:"
          Write-Host $FILTER

          $dll = Get-ChildItem -Path "bin" -Recurse -Filter "Content.IntegrationTests.dll" |
            Where-Object { $_.FullName -notlike "*Benchmarks*" } |
            Select-Object -First 1 -ExpandProperty FullName
          if (-not $dll) {
            Write-Error "${{matrix.shard.name}} shard: could not find Content.IntegrationTests.dll in bin!"
            exit 1
          }
          Write-Host "${{matrix.shard.name}} shard: DLL in use: $dll"

          dotnet test "$dll" --verbosity normal --filter "$FILTER" `
            -- NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed

          Write-Host "${{matrix.shard.name}} shard: dotnet test exited with status=$LASTEXITCODE"
          exit $LASTEXITCODE

  ci-success:
    name: Build & Test Debug
    needs: [ build, integration-tests ]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
