using Content.Client.Lobby.UI;
using System.Linq;
using Content.Client.CMU14.Interface;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    /// <summary>
    ///     The rules a role is taken under, and the button that takes it. Wears the same chrome as
    ///     <see cref="GhostRolesWindow"/> - it is opened by that window and read as part of it.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GhostRoleRulesWindow : DefaultWindow
    {
        [Dependency] private IConfigurationManager _cfg = IoCManager.Resolve<IConfigurationManager>();
        [Dependency] private IStylesheetManager _stylesheetManager = default!;
        [Dependency] private IResourceCache _resourceCache = default!;

        private const int TitleSize = 8;
        private const int ButtonSize = 9;
        private const float ScanlineDepth = 0.9f;

        private readonly CrtScreenControl _shaderPass;
        private readonly Control _cornerTicks;

        private float _timer;
        private readonly GhostRoleKind _ghostRoleKind;

        public GhostRoleRulesWindow(string rules, GhostRoleKind ghostRoleKind, Action<BaseButton.ButtonEventArgs> requestAction)
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Contents.Margin = new Thickness(0);

            _cornerTicks = CrtLobbyTheme.CornerTicks(HivePalette.Accent.WithAlpha(0.55f));
            Ground.AddChild(_cornerTicks);

            _shaderPass = new CrtScreenControl
            {
                Source = Children.OfType<BoxContainer>().First(),
                HorizontalExpand = true,
                VerticalExpand = true,
                Phosphor = HivePalette.Accent,
                Intensity = ScanlineDepth,
                Curvature = 0f,
                Grain = false,
                Roll = false,
                ArtifactAmount = 0f,
            };
            AddChild(_shaderPass);

            _ghostRoleKind = ghostRoleKind;

            // CMU: the button is enabled immediately; the read-the-rules delay is not enforced here.
            SetRules(rules);
            RequestButton.Disabled = false;
            RequestButton.Text = GetButtonText(false);

            ApplyTheme();

            RequestButton.OnPressed += requestAction;
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }


        private void SetRules(string rules)
        {
            TopBanner.SetMessage(FormattedMessage.FromMarkupPermissive(
                $"[color={HivePalette.Text.ToHex()}]{rules}[/color]"));
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }

        private void OnCrtUiEnabledChanged(bool _) => ApplyTheme();

        private void OnCrtUiColorChanged(string _) => ApplyTheme();

        private void ApplyTheme()
        {
            Stylesheet = _stylesheetManager.SheetNano;

            var crt = StyleNano.CrtUiEnabled;
            var header = FindControl<PanelContainer>("WindowHeader");
            var titleLabel = FindControl<Label>("TitleLabel");
            var closeButton = FindControl<TextureButton>("CloseButton");

            if (crt)
                AddStyleClass(StyleNano.StyleClassCrtWindow);
            else
                RemoveStyleClass(StyleNano.StyleClassCrtWindow);

            header.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = HivePalette.Surface2,
                BorderColor = HivePalette.Line,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 5,
                ContentMarginRightOverride = 6,
            };

            titleLabel.FontOverride = HivePalette.Font(_resourceCache, TitleSize);
            titleLabel.FontColorOverride = HivePalette.Accent;
            closeButton.Modulate = HivePalette.TextDim;

            Ground.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = HivePalette.Surface0,
                BorderColor = HivePalette.Line,
                BorderThickness = new Thickness(1, 0, 1, 1),
            };

            ActionBar.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = HivePalette.Surface1,
                BorderColor = HivePalette.Line,
                BorderThickness = new Thickness(0, 1, 0, 0),
                ContentMarginTopOverride = 10,
                ContentMarginBottomOverride = 10,
            };

            TopBanner.AddStyleClass(StyleNano.StyleClassCrtRichText);

            foreach (var child in RulesScroll.Children)
            {
                if (child is ScrollBar bar && !bar.HasStyleClass(StyleNano.StyleClassHiveScrollBar))
                    bar.AddStyleClass(StyleNano.StyleClassHiveScrollBar);
            }

            StyleRequestButton();

            _shaderPass.Visible = crt;
            _cornerTicks.Visible = crt;
        }

        private void StyleRequestButton()
        {
            var enabled = !RequestButton.Disabled;

            RequestButton.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = enabled ? HivePalette.ControlFace(HivePalette.Accent) : HivePalette.Surface1,
                BorderColor = enabled ? HivePalette.Accent : HivePalette.ControlEdge,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 14,
                ContentMarginRightOverride = 14,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 5,
            };

            RequestButton.Label.FontOverride = HivePalette.Font(_resourceCache, ButtonSize);
            RequestButton.Label.FontColorOverride = enabled ? HivePalette.Accent : HivePalette.TextDim;
            RequestButton.Label.HorizontalExpand = true;
            RequestButton.Label.Align = Label.AlignMode.Center;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            if (!RequestButton.Disabled) return;
            if (_timer > 0.0)
            {
                _timer -= args.DeltaSeconds;
                RequestButton.Text = GetButtonText(true);
            }
            else
            {
                RequestButton.Disabled = false;
                RequestButton.Text = GetButtonText(false);
                StyleRequestButton();
            }
        }

        private string GetButtonText(bool timer)
        {
            var messageId = _ghostRoleKind switch
            {
                GhostRoleKind.FirstComeFirstServe => timer
                    ? "ghost-roles-window-request-role-button-timer"
                    : "ghost-roles-window-request-role-button",
                GhostRoleKind.RaffleReady or GhostRoleKind.RaffleInProgress => timer
                    ? "ghost-roles-window-join-raffle-button-timer"
                    : "ghost-roles-window-join-raffle-button",
                GhostRoleKind.RaffleJoined => timer
                    ? "ghost-roles-window-leave-raffle-button-timer"
                    : "ghost-roles-window-leave-raffle-button-confirm",
                _ => throw new ArgumentOutOfRangeException(nameof(_ghostRoleKind),
                    $"Unknown {nameof(GhostRoleKind)} '{_ghostRoleKind}'")
            };

            return timer
                ? Loc.GetString(messageId, ("time", $"{Math.Max(_timer, 0):0.0}"))
                : Loc.GetString(messageId);
        }
    }
}
