using System.Numerics;
using Content.Client.CMU14.Interface;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    /// <summary>
    ///     The banner heading one role: what it is, and how many ways in there are.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GhostRoleInfoBox : PanelContainer
    {
        [Dependency] private IEntityManager _entityManager = default!;
        [Dependency] private IPlayerManager _playerManager = default!;
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        [Dependency] private IUserInterfaceManager _uiManager = default!;
        [Dependency] private IResourceCache _resourceCache = default!;

        private const int TitleSize = 10;
        private const int CountSize = 18;
        private const int KindSize = 7;
        private const float PreviewSize = 48f;

        private readonly string _description;

        private EntityUid? _previewDummy;

        public GhostRoleInfoBox(
            string name,
            string description,
            NetEntity entity,
            string? entityPrototype,
            string? jobPrototype,
            int count,
            bool raffle,
            Color accent)
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            _description = description;

            Title.Text = name;
            CountLabel.Text = count.ToString();
            KindLabel.Text = Loc.GetString(raffle
                ? "cmu-ghost-roles-raffle-label"
                : "cmu-ghost-roles-open-label");

            PreviewFrame.AddChild(CreatePreview(entity, entityPrototype, jobPrototype, name));
            Description.AddStyleClass(StyleNano.StyleClassCrtRichText);

            ApplyTheme(accent);
        }

        public void ApplyTheme(Color accent)
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = HivePalette.Surface1,
                BorderColor = HivePalette.Line,
                BorderThickness = new Thickness(0, 0, 0, 1),
            };

            AccentEdge.PanelOverride = new StyleBoxFlat { BackgroundColor = accent };

            PreviewFrame.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = HivePalette.Surface2,
                BorderColor = HivePalette.Line,
                BorderThickness = new Thickness(1),
            };

            Title.FontOverride = HivePalette.Font(_resourceCache, TitleSize);
            Title.FontColorOverride = HivePalette.TextBright;

            CountLabel.FontOverride = HivePalette.Font(_resourceCache, CountSize);
            CountLabel.FontColorOverride = accent;

            KindLabel.FontOverride = HivePalette.Font(_resourceCache, KindSize);
            KindLabel.FontColorOverride = HivePalette.TextDim;

            // A RichTextLabel takes its font from the stylesheet only, so the colour goes in the markup.
            Description.SetMessage(FormattedMessage.FromMarkupOrThrow(
                $"[color={HivePalette.TextDim.ToHex()}]{FormattedMessage.EscapeText(_description)}[/color]"));
        }

        private Control CreatePreview(NetEntity entity, string? entityPrototype, string? jobPrototype, string fallback)
        {
            if (_entityManager.TryGetEntity(entity, out var uid) &&
                _entityManager.HasComponent<SpriteComponent>(uid.Value) &&
                GhostPreviewHelper.CanUseLiveSprite(_entityManager, _playerManager, uid.Value))
            {
                return CreateSpritePreview(uid.Value);
            }

            if (!string.IsNullOrWhiteSpace(entityPrototype))
            {
                var preview = new EntityPrototypeView
                {
                    SetSize = new Vector2(PreviewSize, PreviewSize),
                    Stretch = SpriteView.StretchMode.Fit,
                    Scale = new Vector2(1.15f, 1.15f),
                };
                preview.SetPrototype(entityPrototype);
                return preview;
            }

            _entityManager.TryGetEntity(entity, out uid);

            if (GhostPreviewHelper.TryCreateJobPreviewDummy(
                    _uiManager,
                    _prototypeManager,
                    _entityManager,
                    uid ?? EntityUid.Invalid,
                    jobPrototype,
                    fallback,
                    out var dummy))
            {
                _previewDummy = dummy;
                return CreateSpritePreview(dummy);
            }

            // Last resort.
            return new Label
            {
                Text = "?",
                Align = Label.AlignMode.Center,
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                MinSize = new Vector2(PreviewSize, PreviewSize),
                FontOverride = HivePalette.Font(_resourceCache, CountSize),
                FontColorOverride = HivePalette.TextFaint,
            };
        }

        private static SpriteView CreateSpritePreview(EntityUid uid)
        {
            var preview = new SpriteView
            {
                SetSize = new Vector2(PreviewSize, PreviewSize),
                OverrideDirection = Direction.South,
                Stretch = SpriteView.StretchMode.Fit,
                Scale = new Vector2(1.15f, 1.15f),
            };
            preview.SetEntity(uid);
            return preview;
        }

        [System.Obsolete]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (!disposing || _previewDummy is not { } dummy)
                return;

            _entityManager.DeleteEntity(dummy);
            _previewDummy = null;
        }
    }
}
