using System;
using Content.Client.CMU14.Interface;
using Content.Client.Stylesheets;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles;

/// <summary>
///     One line for one entity offering a role - where it is, and the two things you can do about it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GhostRoleEntryButtons : PanelContainer
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    private const int RowSize = 9;
    private const int ClockSize = 14;

    private const float BarEpsilon = 0.002f;

    private const int LockGutter = 16;

    private const int LockedMinWidth = 132;

    private readonly GhostRoleKind _kind;
    private readonly uint _playerCount;
    private readonly TimeSpan _raffleEndTime = TimeSpan.MinValue;
    private readonly TimeSpan _raffleDuration;
    private readonly string _location;

    private Color _accent = HivePalette.Accent;
    private string? _clockText;

    public GhostRoleEntryButtons(GhostRoleInfo info)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _kind = info.Kind;
        _location = string.IsNullOrWhiteSpace(info.Location)
            ? Loc.GetString("cmu-ghost-roles-unknown-location")
            : info.Location;

        if (IsActiveRaffle(_kind))
        {
            _playerCount = info.RafflePlayerCount;
            _raffleEndTime = info.RaffleEndTime;
            _raffleDuration = info.RaffleDuration;
        }

        LocationLabel.Text = _location;
        RequestButton.Text = Loc.GetString(RequestMessageId());

        var raffle = IsActiveRaffle(_kind);
        EntrantsLabel.Visible = raffle;
        RaffleBar.Visible = raffle;
        ClockLabel.Visible = raffle;

        if (raffle)
        {
            EntrantsLabel.Text = Loc.GetString("cmu-ghost-roles-raffle-entrants", ("players", _playerCount));
            UpdateCountdown();
        }

        ApplyTheme(_accent);
    }

    /// <summary>
    ///     Repaints the row in <paramref name="accent"/> - its faction's colour, which is also what
    ///     the request button is filled with.
    /// </summary>
    public void ApplyTheme(Color accent)
    {
        _accent = accent;

        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = IsActiveRaffle(_kind) ? HivePalette.RowTint(accent) : Color.Transparent,
            BorderColor = HivePalette.Rule,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        Pip.PanelOverride = new StyleBoxFlat { BackgroundColor = accent };

        LocationLabel.FontOverride = HivePalette.Font(_resourceCache, RowSize);
        LocationLabel.FontColorOverride = HivePalette.Text;

        EntrantsLabel.FontOverride = HivePalette.Font(_resourceCache, RowSize);
        EntrantsLabel.FontColorOverride = HivePalette.TextDim;

        ClockLabel.FontOverride = HivePalette.Font(_resourceCache, ClockSize);
        ClockLabel.FontColorOverride = accent;

        RaffleBarFill.PanelOverride = new StyleBoxFlat { BackgroundColor = accent };
        RaffleBarTrack.PanelOverride = new StyleBoxFlat { BackgroundColor = HivePalette.Surface3 };

        // Both outlined; the accent is the only difference. Follow stays neutral so Request reads as
        // the louder of the two.
        StyleButton(FollowButton, Color.Transparent, HivePalette.ControlText, HivePalette.ControlEdge);
        StyleButton(RequestButton, HivePalette.ControlFace(accent), accent, accent);
    }

    /// <summary>
    ///     The one row control that has to survive being handed a disabled request button: the box is
    ///     an override, so the stylesheet's disabled rule never gets a look in and the greying has to
    ///     happen here.
    /// </summary>
    public void SetRequestDisabled()
    {
        RequestButton.Disabled = true;

        // The right pad is the padlock's seat: GhostRoleButtonsBox draws the icon over this button,
        // so the label has to be held clear of it here.
        RequestButton.MinWidth = LockedMinWidth;
        StyleButton(RequestButton, HivePalette.Surface1, HivePalette.TextDim, HivePalette.ControlEdge, LockGutter);
    }

    private void StyleButton(Button button, Color fill, Color text, Color border, int rightPad = 0)
    {
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = fill,
            BorderColor = border,
            BorderThickness = border == Color.Transparent ? new Thickness(0) : new Thickness(1),
            ContentMarginLeftOverride = 11,
            ContentMarginRightOverride = 11 + rightPad,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 3,
        };

        button.Label.FontOverride = HivePalette.Font(_resourceCache, RowSize);
        button.Label.FontColorOverride = text;
        button.Label.HorizontalExpand = true;
        button.Label.Align = Label.AlignMode.Center;
    }

    private string RequestMessageId()
    {
        return _kind switch
        {
            GhostRoleKind.FirstComeFirstServe => "ghost-roles-window-request-role-button",
            GhostRoleKind.RaffleReady or GhostRoleKind.RaffleInProgress => "ghost-roles-window-join-raffle-button",
            GhostRoleKind.RaffleJoined => "ghost-roles-window-leave-raffle-button-confirm",
            _ => throw new ArgumentOutOfRangeException(nameof(_kind), $"Unknown {nameof(GhostRoleKind)} '{_kind}'"),
        };
    }

    private void UpdateCountdown()
    {
        var timeLeft = _timing.CurTime <= _raffleEndTime
            ? _raffleEndTime - _timing.CurTime
            : TimeSpan.Zero;

        var text = $"{timeLeft.Minutes:0}:{timeLeft.Seconds:00}";
        if (_clockText != text)
        {
            _clockText = text;
            ClockLabel.Text = text;
        }

        var elapsed = _raffleDuration > TimeSpan.Zero
            ? 1f - (float) (timeLeft.TotalSeconds / _raffleDuration.TotalSeconds)
            : 0f;

        var done = Math.Clamp(elapsed, BarEpsilon, 1f - BarEpsilon);
        RaffleBarFill.SizeFlagsStretchRatio = done;
        RaffleBarTrack.SizeFlagsStretchRatio = 1f - done;
    }

    private static bool IsActiveRaffle(GhostRoleKind kind)
    {
        return kind is GhostRoleKind.RaffleInProgress or GhostRoleKind.RaffleJoined;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (IsActiveRaffle(_kind))
            UpdateCountdown();
    }
}
