using Content.Client.Lobby.UI;
using System.Linq;
using System.Numerics;
using Content.Client.CMU14.Interface;
using Content.Client.Stylesheets;
using Content.Shared.CMU14.Ghost.Roles;
using Content.Shared.CCVar;
using Content.Shared.CMU14.Threats;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    /// <summary>
    ///     The ghost roles list: faction categories down a rail, and in the pane a banner per role
    ///     with one line under it for every entity offering that role.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GhostRolesWindow : DefaultWindow
    {
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IEntityManager _entityManager = default!;
        [Dependency] private IStylesheetManager _stylesheetManager = default!;
        [Dependency] private IResourceCache _resourceCache = default!;
        [Dependency] private IPrototypeManager _prototypes = default!;

        private const string OtherCategory = "Other";

        private const int TitleSize = 8;
        private const int RailSize = 9;
        private const int NoteSize = 8;
        private const int MessageSize = 9;

        private const float ScanlineDepth = 0.9f;

        public event Action<GhostRoleInfo>? OnRoleRequestButtonClicked;
        public event Action<GhostRoleInfo>? OnRoleFollow;

        /// <summary>Fired when the ghost presses the call-in button. Runs on each press while enabled.</summary>
        public event Action? OnGhostCallPressed; // CMU14

        private readonly List<EntryState> _entries = new();
        private readonly List<RailEntry> _rail = new();
        private readonly Dictionary<string, int> _categoryCounts = new();

        private string _searchText = string.Empty;

        private string? _selectedCategory;

        private int _availableRoleCount;
        private bool _updatingEntries;
        private Vector2 _entryUpdateScrollValue;

        private readonly CrtScreenControl _shaderPass;
        private readonly Control _cornerTicks;

        public GhostRolesWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Contents.Margin = new Thickness(0);

            _cornerTicks = CrtLobbyTheme.CornerTicks(HivePalette.Accent.WithAlpha(0.55f));
            Ground.AddChild(_cornerTicks);

            _shaderPass = new CrtScreenControl
            {
                // DefaultWindow's own BoxContainer, so the raster covers the title bar too.
                Source = Children.OfType<BoxContainer>().First(),
                HorizontalExpand = true,
                VerticalExpand = true,
                Phosphor = HivePalette.Accent,
                Intensity = ScanlineDepth,
                Curvature = 0f,
                Grain = false,
                Roll = false,
                ArtifactAmount = 0f,
            };
            AddChild(_shaderPass);

            ApplyTheme();

            SearchBar.OnTextChanged += OnSearchTextChanged;
            GhostCallButton.OnPressed += _ => OnGhostCallPressed?.Invoke(); // CMU14
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }


        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }

        private void OnCrtUiEnabledChanged(bool _) => ApplyTheme();

        private void OnCrtUiColorChanged(string _) => ApplyTheme();

        private void ApplyTheme()
        {
            Stylesheet = _stylesheetManager.SheetNano;

            var crt = StyleNano.CrtUiEnabled;
            var header = FindControl<PanelContainer>("WindowHeader");
            var titleLabel = FindControl<Label>("TitleLabel");
            var closeButton = FindControl<TextureButton>("CloseButton");

            if (crt)
                AddStyleClass(StyleNano.StyleClassCrtWindow);
            else
                RemoveStyleClass(StyleNano.StyleClassCrtWindow);

            header.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = HivePalette.Surface2,
                BorderColor = HivePalette.Line,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 5,
                ContentMarginRightOverride = 6,
            };

            titleLabel.FontOverride = HivePalette.Font(_resourceCache, TitleSize);
            titleLabel.FontColorOverride = HivePalette.Accent;
            closeButton.Modulate = HivePalette.TextDim;

            Ground.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = HivePalette.Surface0,
                BorderColor = HivePalette.Line,
                BorderThickness = new Thickness(1, 0, 1, 1),
            };

            FilterBar.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = HivePalette.Surface1,
                BorderColor = HivePalette.Line,
                BorderThickness = new Thickness(0, 0, 0, 1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 7,
                ContentMarginBottomOverride = 6,
            };

            RailPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = HivePalette.Surface1,
                BorderColor = HivePalette.Line,
                BorderThickness = new Thickness(0, 0, 1, 0),
            };

            SearchBar.AddStyleClass(StyleNano.StyleClassHiveLineEdit);
            StyleScrollBars(RailScroll);
            StyleScrollBars(RoleScroll);

            CountLabel.FontOverride = HivePalette.Font(_resourceCache, NoteSize);
            CountLabel.FontColorOverride = HivePalette.TextDim;

            NoRolesMessage.FontOverride = HivePalette.Font(_resourceCache, MessageSize);
            NoRolesMessage.FontColorOverride = HivePalette.TextDim;

            foreach (var entry in _entries)
            {
                var accent = AccentOf(entry.Category);
                entry.Banner.ApplyTheme(accent);
                entry.Instances.ApplyTheme(accent);
            }

            foreach (var rail in _rail)
                StyleRailEntry(rail, rail.Id == _selectedCategory);

            _shaderPass.Visible = crt;
            _cornerTicks.Visible = crt;
        }

        private static void StyleScrollBars(Control scroll)
        {
            foreach (var child in scroll.Children)
            {
                if (child is ScrollBar bar && !bar.HasStyleClass(StyleNano.StyleClassHiveScrollBar))
                    bar.AddStyleClass(StyleNano.StyleClassHiveScrollBar);
            }
        }

        public void ClearEntries()
        {
            _availableRoleCount = 0;
            _entries.Clear();
            _categoryCounts.Clear();
            EntryContainer.DisposeAllChildren();

            if (_updatingEntries)
                return;

            RebuildRail();
            UpdateVisibleEntries();
        }

        // CMU14 method
        /// <summary>Shows or hides the ghost call-in row from the menu state, with the gate that still blocks it.</summary>
        public void UpdateGhostCall(GhostThirdPartyCallState? state)
        {
            GhostCallBox.Visible = state != null;
            if (state is not { } call)
                return;

            if (call.Pending)
            {
                GhostCallButton.Text = Loc.GetString("cmu-ghost-call-pending");
                GhostCallButton.Disabled = true;
                GhostCallStatus.Text = string.Empty;
            }
            else if (call.Available)
            {
                GhostCallButton.Text = Loc.GetString("cmu-ghost-call-button");
                GhostCallButton.Disabled = false;
                GhostCallStatus.Text = Loc.GetString("cmu-ghost-call-status-available");
            }
            else
            {
                GhostCallButton.Text = Loc.GetString("cmu-ghost-call-button");
                GhostCallButton.Disabled = true;
                GhostCallStatus.Text = call.MinutesLeft > 0
                    ? Loc.GetString("cmu-ghost-call-status-time", ("minutes", call.MinutesLeft))
                    : Loc.GetString("cmu-ghost-call-status-dead",
                        ("dead", call.Dead), ("required", call.RequiredDead));
            }
        }

        public void SaveCollapsibleBoxesStates()
        {
        }

        public void RestoreCollapsibleBoxesStates()
        {
        }

        /// <summary>
        ///     Adds one role: a banner, and a line for each of the <paramref name="roles"/> entities
        ///     offering it.
        /// </summary>
        public void AddEntry(
            string name,
            string description,
            string? category,
            bool hasAccess,
            FormattedMessage? reason,
            IEnumerable<GhostRoleInfo> roles,
            SpriteSystem spriteSystem)
        {
            var infos = roles.ToList();
            if (infos.Count == 0)
                return;

            _availableRoleCount += infos.Count;

            var categoryId = ResolveCategory(category);
            var accent = AccentOf(categoryId);
            var raffle = infos.Any(role => role.Kind != GhostRoleKind.FirstComeFirstServe);

            var banner = new GhostRoleInfoBox(
                name,
                description,
                infos[0].Entity,
                infos[0].EntityPrototype,
                infos[0].JobPrototype,
                infos.Count,
                raffle,
                accent);

            var instances = new GhostRoleButtonsBox(hasAccess, reason, infos, spriteSystem, accent);
            instances.OnRoleSelected += info => OnRoleRequestButtonClicked?.Invoke(info);
            instances.OnRoleFollow += info => OnRoleFollow?.Invoke(info);

            var entry = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 0,
                Children = { banner, instances },
            };

            EntryContainer.AddChild(entry);

            // Locations are searchable too - "medbay" is a reasonable thing to type.
            var locations = string.Join(
                " ",
                infos.Select(role => role.Location).Where(location => !string.IsNullOrEmpty(location)));

            var searchText = $"{name} {description} {CategoryName(categoryId)} {locations}";

            _entries.Add(new EntryState(entry, banner, instances, searchText, categoryId));
            _categoryCounts[categoryId] = _categoryCounts.GetValueOrDefault(categoryId) + infos.Count;

            if (_updatingEntries)
                return;

            RebuildRail();
            UpdateVisibleEntries();
        }

        public void BeginEntryUpdate()
        {
            _entryUpdateScrollValue = RoleScroll.GetScrollValue(ignoreVisible: true);
            _updatingEntries = true;
            ClearEntries();
        }

        public void EndEntryUpdate()
        {
            _updatingEntries = false;
            RebuildRail();
            UpdateVisibleEntries();

            RoleScroll.SetScrollValue(_entryUpdateScrollValue);
            RoleScroll.HScrollTarget = _entryUpdateScrollValue.X;
            RoleScroll.VScrollTarget = _entryUpdateScrollValue.Y;
        }

        private void RebuildRail()
        {
            RailList.DisposeAllChildren();
            _rail.Clear();

            // A selection whose category has just emptied out would otherwise leave the pane blank.
            if (_selectedCategory != null && !_categoryCounts.ContainsKey(_selectedCategory))
                _selectedCategory = null;

            AddRailEntry(null, Loc.GetString("cmu-ghost-roles-all-category"), HivePalette.Accent, _availableRoleCount);

            var ordered = _categoryCounts
                .OrderBy(pair => WeightOf(pair.Key))
                .ThenBy(pair => CategoryName(pair.Key));

            foreach (var (id, count) in ordered)
            {
                AddRailEntry(id, CategoryName(id), AccentOf(id), count);
            }

            foreach (var rail in _rail)
                StyleRailEntry(rail, rail.Id == _selectedCategory);
        }

        private void AddRailEntry(string? id, string name, Color accent, int count)
        {
            var box = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent,
                BorderColor = HivePalette.Rule,
                BorderThickness = new Thickness(0, 0, 0, 1),
                ContentMarginLeftOverride = 0,
                ContentMarginRightOverride = 12,
                ContentMarginTopOverride = 9,
                ContentMarginBottomOverride = 8,
            };

            var marker = new PanelContainer
            {
                MinWidth = 2,
                Visible = false,
                PanelOverride = new StyleBoxFlat { BackgroundColor = accent },
            };

            var pip = new PanelContainer
            {
                MinSize = new Vector2(6, 6),
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(10, 0, 0, 0),
                PanelOverride = new StyleBoxFlat { BackgroundColor = accent },
            };

            var nameLabel = new Label
            {
                Text = name,
                ClipText = true,
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true,
                Margin = new Thickness(8, 0, 0, 0),
            };

            var countLabel = new Label
            {
                Text = count.ToString(),
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(10, 0, 0, 0),
            };

            var button = new ContainerButton
            {
                HorizontalExpand = true,
                StyleBoxOverride = box,
                Children =
                {
                    new BoxContainer
                    {
                        Orientation = LayoutOrientation.Horizontal,
                        SeparationOverride = 0,
                        HorizontalExpand = true,
                        Children = { marker, pip, nameLabel, countLabel },
                    },
                },
            };

            var rail = new RailEntry(id, box, marker, nameLabel, countLabel, accent);
            _rail.Add(rail);

            button.OnPressed += _ => SelectCategory(id);
            button.OnMouseEntered += _ =>
            {
                if (!marker.Visible)
                    box.BackgroundColor = HivePalette.Surface2;
            };
            button.OnMouseExited += _ =>
            {
                if (!marker.Visible)
                    box.BackgroundColor = Color.Transparent;
            };

            RailList.AddChild(button);
        }

        private void SelectCategory(string? id)
        {
            _selectedCategory = id;

            foreach (var rail in _rail)
                StyleRailEntry(rail, rail.Id == id);

            UpdateVisibleEntries();
        }

        private void StyleRailEntry(RailEntry rail, bool selected)
        {
            rail.Marker.Visible = selected;
            rail.Box.BackgroundColor = selected ? HivePalette.Surface2 : Color.Transparent;

            rail.Name.FontOverride = HivePalette.Font(_resourceCache, RailSize);
            rail.Name.FontColorOverride = selected ? HivePalette.TextBright : HivePalette.TextDim;

            rail.Count.FontOverride = HivePalette.Font(_resourceCache, NoteSize);
            rail.Count.FontColorOverride = selected ? rail.Accent : HivePalette.TextFaint;
        }

        private void UpdateVisibleEntries()
        {
            CountLabel.Text = Loc.GetString(
                "cmu-ghost-roles-summary",
                ("roles", _availableRoleCount),
                ("categories", _categoryCounts.Count));

            var searching = !string.IsNullOrWhiteSpace(_searchText);
            var anyVisible = false;

            foreach (var entry in _entries)
            {
                var visible = searching
                    ? entry.SearchText.Contains(_searchText, StringComparison.OrdinalIgnoreCase)
                    : _selectedCategory == null || entry.Category == _selectedCategory;

                entry.Control.Visible = visible;
                anyVisible |= visible;
            }

            RoleScroll.Visible = anyVisible;
            NoRolesMessage.Text = _availableRoleCount == 0
                ? Loc.GetString("ghost-roles-window-no-roles-available-label")
                : Loc.GetString("ghost-roles-window-no-results-label");
            NoRolesMessage.Visible = !anyVisible;
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text.Trim();
            UpdateVisibleEntries();
        }

        private string ResolveCategory(string? category)
        {
            return !string.IsNullOrEmpty(category) && _prototypes.HasIndex<GhostRoleCategoryPrototype>(category)
                ? category
                : OtherCategory;
        }

        private Color AccentOf(string category)
        {
            return HivePalette.Readable(_prototypes.TryIndex<GhostRoleCategoryPrototype>(category, out var proto)
                ? proto.Color
                : HivePalette.Accent);
        }

        private string CategoryName(string category)
        {
            return _prototypes.TryIndex<GhostRoleCategoryPrototype>(category, out var proto)
                ? Loc.GetString(proto.Name)
                : category;
        }

        private int WeightOf(string category)
        {
            return _prototypes.TryIndex<GhostRoleCategoryPrototype>(category, out var proto)
                ? proto.Weight
                : int.MaxValue;
        }

        private readonly record struct EntryState(
            Control Control,
            GhostRoleInfoBox Banner,
            GhostRoleButtonsBox Instances,
            string SearchText,
            string Category);

        /// <summary>One rail entry. <see cref="Id"/> is null for the "all roles" entry.</summary>
        private sealed record RailEntry(
            string? Id,
            StyleBoxFlat Box,
            PanelContainer Marker,
            Label Name,
            Label Count,
            Color Accent);
    }
}
