using System.Collections.Generic;
using System.Numerics;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles;

/// <summary>
///     The instance lines under one role's banner - one per entity offering it, never merged.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GhostRoleButtonsBox : BoxContainer
{
    private readonly List<GhostRoleEntryButtons> _rows = new();
    private readonly bool _hasAccess;

    public event Action<GhostRoleInfo>? OnRoleSelected;
    public event Action<GhostRoleInfo>? OnRoleFollow;

    public GhostRoleButtonsBox(
        bool hasAccess,
        FormattedMessage? reason,
        IEnumerable<GhostRoleInfo> roles,
        SpriteSystem spriteSystem,
        Color accent)
    {
        RobustXamlLoader.Load(this);
        _hasAccess = hasAccess;

        foreach (var role in roles)
        {
            var row = new GhostRoleEntryButtons(role);
            row.RequestButton.OnPressed += _ => OnRoleSelected?.Invoke(role);
            row.FollowButton.OnPressed += _ => OnRoleFollow?.Invoke(role);

            if (!hasAccess)
            {
                row.SetRequestDisabled();

                if (reason != null && !reason.IsEmpty)
                {
                    var tooltip = new Tooltip();
                    tooltip.SetMessage(reason);
                    row.RequestButton.TooltipSupplier = _ => tooltip;
                }

                // Not HorizontalExpand: expanding makes this span the whole button and defeats KeepCentered.
                row.RequestButton.AddChild(new TextureRect
                {
                    TextureScale = new Vector2(0.4f, 0.4f),
                    Stretch = TextureRect.StretchMode.KeepCentered,
                    Texture = spriteSystem.Frame0(new SpriteSpecifier.Texture(new("/Textures/Interface/Nano/lock.svg.192dpi.png"))),
                    HorizontalAlignment = HAlignment.Right,
                    VerticalAlignment = VAlignment.Center,
                });
            }

            _rows.Add(row);
            AddChild(row);
        }

        ApplyTheme(accent);
    }

    public void ApplyTheme(Color accent)
    {
        foreach (var row in _rows)
        {
            row.ApplyTheme(accent);

            // After ApplyTheme, never before: it hands every request button the same filled face.
            if (!_hasAccess)
                row.SetRequestDisabled();
        }
    }
}
